### ISSUE TITLE
Startup issue on pixel 4a

### ISSUE THREAD

**Issue by mcmilnick** [lrorpilla/jidoujisho#1]
Using Android version 11 currently.
Does not start at all.

**Comment by lrorpilla** [comment]
It seems that Android 11 users are unable to start the app. This is a report I've received from Samsung and Google users alike, and seems to be related to target SDK 29 used (Android 10).

The app demands access to external storage and doesn't comply with the enforcement of scoped storage in target SDK 30. Currently, I believe the app is targeting Android 10 and has a minimum version of 7.0 Nougat to run.

I'll be investigating what I can use to allow a broader audience of users to install and use the app.

**Comment by lrorpilla** [comment]
[0.3.2 has been released](https://github.com/lrorpilla/jidoujisho/releases/tag/0.3.2-beta) which should allow Android 11 users to run and use the app. This feature requires a workaround in regards to storage permissions detailed [in the release notes](https://github.com/lrorpilla/jidoujisho/releases/tag/0.3.2-beta).

The app has been tested to work on an Android 11 emulator, so I am closing this issue. If there are any more problems related to running the app on Android 11, please comment here.

**Comment by mcmilnick** [comment]
Works a treat. Thanks for the quick bugfix :)
