### ISSUE TITLE
Be able to select the screenshot when exporting multiple subtitles in a same card.

### ISSUE THREAD

**Issue by Hexavall** [lrorpilla/jidoujisho#10]
When I export multiple subtitles in a same card, the screenshot is taken from the first subtitle. May be convenient to be able to select the screenshot based on one of the subtitles that I selected to be export on the same card just touching the subtitle, or just be able to take a screenshot freely and put it into the card.

Thanks!

**Comment by lrorpilla** [comment]
I have implemented this feature in [0.13.2](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.2-beta).

See the relevant line in the release notes:
* **(New Feature) Image Select for Multiple Subtitle Export** - Users may now swipe left or right to pick an image when exporting multiple subtitles, the image is taken from the mean subtitle time, or between start and end time

With that, I am closing this issue.
