### ISSUE TITLE
[Feature Request] Separate fields for word audio and sentence audio

### ISSUE THREAD

**Issue by dkaknbk** [lrorpilla/jidoujisho#100]
For cards created from the video player, would it be possible to have a separate card field for audio for the mined word (e.g. forvo) and for the sentence audio ripped from a video file? That would help me to emulate my Yomichan card setup fairly  closely and would make conversion considerably easier. If you don't want to make your default template too complicated, it would be fine to have both files in the same field, too, i.e. have the word audio file first, followed by the ripped sentence audio file. Current behaviour seems to disable the ability to add word audio if ripped sentence audio is already present. Also, support for frequency lists (e.g. Innocent Corpus) and a corresponding field would be very useful, as well.

Thanks for the great work, I really enjoy using your application in its current iteration and am looking forward to the next update!

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. You are free to re-open if you feel your issue has not been solved. Relevant line in release notes: 
- Added a new field for Sentence Audio which is used specifically for exporting subtitle audio from video, included as part of the default profile.
- Renamed the Audio field to the Term Audio field.
- Existing users are advised to add the Sentence Audio field as the last field to their default profile in order for the app to not reset the profile every reinstallation. Users that wish to add this field to their cards must edit their card type CSS.
