### ISSUE TITLE
[Feature Request] A more frictionless, faster way to export cards

### ISSUE THREAD

**Issue by ChubYee** [lrorpilla/jidoujisho#101]
Right now, for exporting cards when watching something, it takes a bit of steps (not a lot, but it'd be nice if I didn't have to open to the card exporter window). The steps are:

1. Tap the word you want to add/export to AnkiDroid
2. Wait for it to pop up the definition and read/confirm what it means
3. Tap the screen anywhere, to reveal the "⋮" icon at the bottom right of the screen
4. Tap the "⋮" icon
5. Tap "Create Card from Context"
6. Wait while it's "Preparing Card"
6½. It pops up/takes you to the Card Creator window
7. Tap "Export Card"

Process = 4 taps, a bit of waiting because of the Card Creator window, and then a final tap

I feel like this could be shortened to make the steps:

1. Tap the word you want to add/export to AnkiDroid

2. Wait for it to pop up the dictionary and read/confirm what it means, 
[NEW FEATURE]: also have a 1-tap-create-and-export checkmark button that appears on the screen when the dictionary definition also pops up (hopefully also make a setting so one could customize it's size and position-on-the-screen to their liking)

3. Tap that checkmark button, (which automatically creates and exports the card in the background, no Card Creator pop-up, and when it's done, you get a super quick little message that confirms that it successfully exported the card)

---------------------------------------------------------------------------

Moving on to reading/manga card creation/exportation

Currently, when on a manga page to create/export a card, the steps are:

1. Tap the screen to reveal the little scan square icon at the bottom right of the screen (alternatively, you can just hold the screen to activate the scan feature, but I'll talk more about this later)

2. Tap that scan square icon 

3. Drag your finger to create a scan area for the ocr and wait for it to give the list of words scanned

4. From the list of words scanned, tap the specific word/kanji you want to know/export to AnkiDroid

5. Tap the "Search" button

6. Wait for it to pop up the definition and read/confirm what it means

7. Tap the "⋮" icon at the bottom right of the screen

8. Tap "Create Card from Context"

9. Wait while it's "Preparing Card"

9½. It pops up/takes you to the Card Creator window

10. Tap "Export Card"

I feel like this could be shortened to make the steps:

1. [New/tweaked feature]: NEW Hold + drag to ocr the word you want to add/export to AnkiDroid 
(right now, the current steps of "hold-scanning" are: 
you need to put and hold your finger on the screen somewhere, 
wait a little, 
take your finger off the screen, 
and then re-put it back and hold it on the screen, somewhere you are going to create/place the corner of the scan window/frame, 
and then finally, drag your finger to size the window/frame to your needs,
and then release

The current process=hold, release, rehold, drag, release

With this new/tweaked feature, the only steps would be: put and hold your finger on the screen where you're wanting to scan,
then just dragging it to create the window/frame
and then release

New process=hold, drag, and then release

So anyway, back to hypothetical new-and-improved fastest method of creating/exporting cards from manga/reader viewer to AnkiDroid. Steps:

1. Use the new/tweaked hold + drag process (most efficient way)

2. From the list of words scanned, instead of single tapping the specific word/kanji and then moving your finger to tap the search button, you could ALSO just double tap the specific word/kanji to search it, that way you don't need to move your finger across the screen and tap multiple buttons.

3. Wait for it to pop up the dictionary and read/confirm what it means
(This is where you would also implement the checkmark 1-tap-create-and-export button from earlier that pops up when the dictionary does)

4. Tap the checkmark button and whualaaaa, exporting cards never felt so fast 😭 . 

5. Onegaishimasu 🙇‍♂️ 

![export202204281245129720](https://user-images.githubusercontent.com/104586776/165820863-5d31d2d6-5a83-46e1-8b62-d37d96c83477.png)
![export202204281536399650](https://user-images.githubusercontent.com/104586776/165841525-56851831-37db-4cb0-93c2-e9bc2a12bbc0.png)

Customize option: ![export202204281602059020](https://user-images.githubusercontent.com/104586776/165845416-3e387834-edf7-4d47-942b-7813ac7ef05f.png)

If you read all this, 🙇‍♂️ . If you implement this 1-tap-create-and-export button that has customization settings that pops up when the dictionary does, and this new/tweaked hold+drag feature, take my money ☕

**Comment by ChubYee** [comment]
![export202204281536399650](https://user-images.githubusercontent.com/104586776/165841348-22569c82-1039-4674-aad4-5b02de645b48.png)

**Comment by ChubYee** [comment]
Take my money. Is it possible to become a beta tester for future releases?

**Comment by lrorpilla** [comment]
I have no formal arrangements that allow one to officially beta test a new release, but I may let you know when an upcoming release is ready. The next release is coming along well and there is progress, but still some time far away.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant lines in release notes.

- Quick Actions allows users to quickly perform tasks for a certain dictionary result. These may be set while editing the enhancements of the Card Creator. The new Quick Action system provides developers with a layer of abstraction for easily adding more actions should they wish to do so.
- Card Creator - Allows users to pick a word, show a dictionary result and then open the Creator with prefilled information corresponding to the word, complete with Reading, Meaning, Image, Audio and more.
- Instant Export - Allows users to quickly export the word, and have the fields be prefilled according to the word and the user's auto enhancements, without opening the Card Creator.
