### ISSUE TITLE
Local Files stay in loading screen forever

### ISSUE THREAD

**Issue by Specki123** [lrorpilla/jidoujisho#103]
I am using the version 1.1.11. I downloaded the jidoujisho_chisa-1_1_11_arm.apk and I´m on Xiaomi Redmi 9A Android version 10, 
MIUI version 12.0.18.

I just downloaded the app yesterday when i first played a local mp4 file it worked but i couldnt load external subtitles.
Then I renamed the mp4 files and the srt files to the same name and now when I tried playing the mp4 files they just stay in loading screen forever.  Youtube videos work fine though,

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that your issue is still present in 2.0, feel free to open.
