### ISSUE TITLE
Video player issue

### ISSUE THREAD

**Issue by ChubYee** [lrorpilla/jidoujisho#104]
https://user-images.githubusercontent.com/104586776/167395713-c6c5459d-790d-4da9-8d73-1e6de2b2eed7.mp4

When I open the mkv using VLC video player, everything looks and runs smooth and perfectly fine. But when I play it with jidoujisho, it's laggy, choppy, stuttery, and greyed. It might be because of how "detailed" the BD-Rip is, and the jidoujisho video player is having a hard time processing all of the information.

**Comment by lrorpilla** [comment]
I believe there is an update in the video player package that I use that will allow me to improve the performance of the player in an upcoming release.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

The new version includes an updated version of the video player package I use (flutter_vlc_player), which implements hybrid composition and have performance fixes that should fix this significantly.
