### ISSUE TITLE
[Feature Request] share images into app

### ISSUE THREAD

**Issue by Sakusuke** [lrorpilla/jidoujisho#105]
Requesting the ability to share images from other apps in jidoujisho. The normal Android share feature. Would be useful for people who use web browser or tachiyomi reader for manga or for screenshots. 
Could automate it even more with an option to automatically open the crop interface or OCR selected area, but normal share feature would be great enough.

**Comment by lrorpilla** [comment]
This feature is now returned in **[2.2.8](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2)**.
