### ISSUE TITLE
[Feature Request] Manage Subtitle Tracks

### ISSUE THREAD

**Issue by LHeider** [lrorpilla/jidoujisho#106]
Requesting the ability to manage (delete) loaded external subtitles from a video. 

Scenario: I have loaded multiple different subtitle files to a local video (to choose the one with the best accuracy/timing), but now I have too many to remember which is the best one.

Alternative scenario: I've accidentally loaded the wrong subtitle track to my video.

If we can remove subtitle tracks from a video via long-press or swipe (or by any other means), this would be a very helpful feature!

![ExternalSubtitles](https://user-images.githubusercontent.com/104459553/173090002-51daea73-3dfe-4045-8c5d-5dc7676a2601.jpg)

**Comment by lrorpilla** [comment]
The player state is temporary and this really comes down to user error, so unfortunately I think I have to turn this down.
