### ISSUE TITLE
Yomichan Frequncy list support

### ISSUE THREAD

**Issue by OltiP2** [lrorpilla/jidoujisho#108]
Like this
![Screenshot_20220623-031134_Chrome](https://user-images.githubusercontent.com/97410429/175186430-d9b76325-88bf-45e1-a791-4d79d2752c5c.jpg)
![Screenshot_20220623-031242_Chrome](https://user-images.githubusercontent.com/97410429/175186440-5332c449-4a2b-4619-914d-a9df54609bd6.jpg)

**Comment by lrorpilla** [comment]
I can confirm this is arriving in the next version.

**Comment by OltiP2** [comment]
Ok 👍
