### ISSUE TITLE
Ebook reader add cards to Anki

### ISSUE THREAD

**Issue by ChubYee** [lrorpilla/jidoujisho#109]
Is there a way to add words/create cards when using the Ebook reader?

**Comment by lrorpilla** [comment]
Yeah, you can highlight text and tap on Creator. If you want to try a preview of the next version that improves upon this (only the reader and improved dictionary and creator are available at this time), send me an e-mail.

**Comment by ChubYee** [comment]
😱

**Comment by lrorpilla** [comment]
Closed as issue has been answered.
