### ISSUE TITLE
Better subscriptions import

### ISSUE THREAD

**Issue by Hexavall** [lrorpilla/jidoujisho#11]
Would be convenient to be able to import the subscriptions directly from youtube, newpipe, and other similar youtube-based apps.

Thanks!

**Comment by lrorpilla** [comment]
I don't intend to involve pulling any account data into the application as I think it's very high maintenance, and I don't want to be handling any private user data. Users can get a list of channels they subscribe from third party tools and use the built-in import/export feature.

Have to turn this one down, unfortunately.

**Comment by lrorpilla** [comment]
As someone shared in the Refold Discord, you can use [this Chrome extension](https://chrome.google.com/webstore/detail/youtube-subscriptions-exp/dhpojdmnffaocepmljcdcongdmkjblan/related) to extract your channel IDs.

This will get you a text snippet of this format:
```txt
Channel 1: https://youtube.com/channel/channelID1here
Channel 2: https://youtube.com/channel/channelID2here
```
So, you can use RegEx to get rid of the text leading up to the channel ID:
1. Replace all `.*(?=/)` with nothing
2. Replace all `/` with nothing

This will get you a clean text file with just your channel IDs that you can import into the app. If you need any help with this, I would be happy to help.
