### ISSUE TITLE
Can't add new books to ttu-reader

### ISSUE THREAD

**Issue by AlbaNemori** [lrorpilla/jidoujisho#110]
The bar at the top that allowed you to add books has disappered and doesn't pop up no matter where I tap. Furthermore, I sometimes have trouble making the bar appear even when I'm reading a book. The only solution is to exit the reader, then reopen to make it appear but this does not work for the menu.

**Comment by lrorpilla** [comment]
Hi, I recommend using the 2.0 preview going forward for reading. This includes the reader and new dictionary, but note that it doesn't include player and reader functionalities yet. This will be reintroduced in a proper 2.0 release.

https://drive.google.com/file/d/17ZZkh3THq8jGzebbbxg6Ov0MD0HOTebh/view?usp=drivesdk

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.
