### ISSUE TITLE
Look ups take a lot of time

### ISSUE THREAD

**Issue by Specki123** [lrorpilla/jidoujisho#111]
This is just a general question. Why do word look ups sometimes take 2-5 seconds and sometimes about a minute? Internet connection is not the issue because it does work without internet since the dictionary is downloaded. Is my phone the issue?

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. You are free to re-open if you feel your issue has not been solved. Relevant line in release notes: 
- The dictionary search algorithm has been overhauled, with dramatic improvements to query speed, performance and results.
