### ISSUE TITLE
Jidoujisho not opening

### ISSUE THREAD

**Issue by T1CkShot** [lrorpilla/jidoujisho#112]
I've uninstalled the 1.1 version then installed 2.0. But after opening the app it's stuck in the splash screen. If I minimize the app and then open again it shows a black screen.

**Comment by lrorpilla** [comment]
When you start the app, it asks you for permissions to start working. Did you see and accept these permissions? There are three permissions you need to accept, two below Android 12.

The app has been tested to launch on a device as old as Android 7. I need more information to work out your issue. What happens when you uninstall and retry again?

**Comment by lrorpilla** [comment]
Might also be useful to know what architecture you're trying to install and if you've tried others.

**Comment by Chrollo-debug** [comment]
I know I have nothing to do with the project, but is there a way to put an English dictionary in the app or is it only Portuguese?

**Comment by lrorpilla** [comment]
jidoujisho 2.0 only supports Japanese for now. I am looking for contributors that are interested to support for more languages.

**Comment by T1CkShot** [comment]
I've tried reinstalling but same issues. I'm on armeabi and I've tried the other ones too. I did give the 2 permission that was asked. The phone has android 8.1.0

**Comment by lrorpilla** [comment]
Hi T1Ckshot. I have identified an issue with the database I am using (Isar) not working on 32-bit devices (armeabi). I have a fix and I will work on it as soon as I am free.

**Comment by lrorpilla** [comment]
Hi T1ckshot. There is a new hotfix under the 2.0 release. Can you try it?

**Comment by T1CkShot** [comment]
Yes it's working fine now 😊

**Comment by lrorpilla** [comment]
Glad to hear it.
Issue closed.

**Comment by Chrollo-debug** [comment]
Hey ,I wanted to know if in the application there is a way to put all the words separately in anki at once, because creating one card at a time in each scene takes a long time

**Comment by Chrollo-debug** [comment]
I wanted to know if there is any group about the app, because I feel like I'm getting in the way by commenting here
