### ISSUE TITLE
When importing .ass subtitle loads old one

### ISSUE THREAD

**Issue by OltiP2** [lrorpilla/jidoujisho#115]
When this bug happened i thought it was with every subtitle but then i realized as seen in the video it was only with .ass files(i have only tried with .ass and .srt)
Video:
https://drive.google.com/file/d/1XfUEu-49vix4gXe3GO9Jn2hjkeDfBJ36/view

**Comment by lrorpilla** [comment]
I'm looking to address this in a bug fix release.

**Comment by lrorpilla** [comment]
I believe this issue was addressed in [**2.0.2**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0), if the problem still occurs, feel free to re-open this issue.
