### ISSUE TITLE
Deleting dictionaries makes look-up history clear itself

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#117]
Whenever I delete a dictionary my look-up history is deleted.
Take a look at this video:

https://user-images.githubusercontent.com/84395172/189551987-8aaba2f0-eb8e-4ad4-ae24-f168f6108a94.mp4

**Comment by Feripe-a** [comment]
I forgot to say that I'm happy that you're back on this big project of yours.

**Comment by TheAtlasRises** [comment]
This is not an issue, it's intended behavior according to the patch notes for this version. 

> Deleting a dictionary now completely clears dictionary history. This is necessary as some entries in history may be dependent on a given dictionary's data in order to be viewed.

**Comment by lrorpilla** [comment]
The delete prompt when you try to delete a dictionary also states that your results will be cleared. This behaviour is to make sure that there won't be any issues with items in history as they would need to filter and delete out information present in the dictionary you just deleted. It's much faster and less errorprone to delete and clear everything.

**Comment by Feripe-a** [comment]
I see.
