### ISSUE TITLE
Lyrics don't appear

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#118]
https://user-images.githubusercontent.com/84395172/189552311-789f9361-c0d6-4f7d-af6e-2ef4911c15de.mp4

**Comment by Feripe-a** [comment]
https://user-images.githubusercontent.com/84395172/189552403-34cbdd9a-735a-4d73-b805-535179d06d90.mp4

**Comment by lrorpilla** [comment]
Can you send a screenshot of your app's permissions?

**Comment by Feripe-a** [comment]
![Screenshot_2022-09-11-21-38-22-733_com google android permissioncontroller](https://user-images.githubusercontent.com/84395172/189556449-f643385c-c442-46eb-8bf4-35836e6c1f6f.jpg)
![Screenshot_2022-09-11-21-38-30-110_com miui securitycenter](https://user-images.githubusercontent.com/84395172/189556450-4852c41a-a574-4350-a1e7-01d4be378270.jpg)
![Screenshot_2022-09-11-21-40-37-359_com android settings](https://user-images.githubusercontent.com/84395172/189556452-1212f768-7ba4-41a1-951e-9e6514ed2609.jpg)
![Screenshot_2022-09-11-21-40-40-890_com android settings](https://user-images.githubusercontent.com/84395172/189556455-d5dc2f83-8827-4d0b-a86b-9d096bd36c6b.jpg)

**Comment by lrorpilla** [comment]
I'm closing this issue as it has become a bit dated but I welcome you to re-open if you wish as it is possibly unresolved.
