### ISSUE TITLE
Can’t open EPUB file 

### ISSUE THREAD

**Issue by matthi00** [lrorpilla/jidoujisho#119]
https://user-images.githubusercontent.com/26419857/189772153-16efe69a-1089-4049-896a-24dfa5ebcc3a.mp4

**Comment by lrorpilla** [comment]
Can you share the files in question? Do they import from a browser in TTU just fine?

**Comment by lrorpilla** [comment]
May I also know your Android version and build?

**Comment by matthi00** [comment]
https://drive.google.com/drive/folders/1T1MpUSLpJBG6VBCeks77Za1Jeq2ld3qm
Sorry i don't know how to test it.
I have a redmi note 8T with android 11 miui 12.5.5

**Comment by lrorpilla** [comment]
Can you try using a different file picker to pick an EPUB and see how that works? Or you can pick it from internal storage and specifically select the files you've picked. This could be an issue with the OS picker.

**Comment by lrorpilla** [comment]
I believe this was fixed in **[2.1](https://github.com/lrorpilla/jidoujisho/releases/tag/2.1)**:
- Fixed an issue where the app may do nothing after making a selection when using a file picker.

If you still experience this issue, feel free to re-open.
