### ISSUE TITLE
Bug when I rotate the phone while video is loading.

### ISSUE THREAD

**Issue by Hexavall** [lrorpilla/jidoujisho#12]
When the video is loading and I rotate the phone without having the auto-rotation option activated, for some reason the video player detects it and this bug happens. The audio is good, but the image stills the same for the rest of the video.
![Screenshot_20210424-034636](https://user-images.githubusercontent.com/75350161/115950294-ac91e380-a4da-11eb-94d7-253a7c9301a7.png)

**Comment by lrorpilla** [comment]
I'll investigate this and attempt to reproduce this but in my experience, anything involving orientation is `flutter_vlc_player` territory. The user can always back out and try again -- and the video does load in later on when the player renderer is ready to show a frame.

**Comment by lrorpilla** [comment]
I can't seem to reproduce this issue. The orientation shifts before the player has initialized. 

I force this change before startup so once the player is present in the screen, the user cannot rotate to portrait and mess up the player widget. So, I am probably at the mercy of the behavior of `flutter_vlc_player` when rotating and how the OS handles orientation changes.

As a mitigation for this issue, the orientation is now forced in the loading screen -- this should ensure that when the player loads in, it will absolutely be in landscape and not somewhere in between.

**Comment by lrorpilla** [comment]
I have implemented a mitigation for this in [0.13.3](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.3-beta).

See the relevant line in the release notes:
* Moved landscape lock earlier from video player screen initialization to give the OS time to adjust the orientation

With that, I am closing this issue.
