### ISSUE TITLE
Manual selection does not result in pop-up

### ISSUE THREAD

**Issue by Jarods-language-journey** [lrorpilla/jidoujisho#122]
Android Version: 12
Phone: Galaxy S22 Ultra (latest Samsung update)
App version: Yuuna (jidoujisho_yuuna_2_0_0-arm64.apk)

Heyo! I'm having an issue with the reader wherein I'm not able to look up text manually. It only allows for tap-to-select. Attached is a screen capture showing this behavior. I've reinstalled the app, made sure permissions were given, and tried other books but this still occurs.

https://user-images.githubusercontent.com/80096108/190204178-ef547c7d-b435-4863-92d1-43ce5b32442e.mp4

This only occurs when reading. For example, I am able to properly highlight and lookup sentences that pop up in the dictionary.

https://user-images.githubusercontent.com/80096108/190207191-1d47fce1-310e-406e-98fd-973a1d06b9a4.mp4

**Comment by lrorpilla** [comment]
I can't seem to replicate this on a stock Android 12 emulator.

**Comment by TheAtlasRises** [comment]
Maybe it's a Samsung specific bug? Same thing here, testing on an A52s device.

https://user-images.githubusercontent.com/106642434/190926034-67cc30f7-91d3-420b-8a00-da5cf99a0d2f.mp4

**Comment by lrorpilla** [comment]
@TheAtlasRises @Jarods-language-journey 
I think [this](**https://drive.google.com/file/d/1MRqGP71PDGxeFtc_SQSJGahve4PUyv25/view?usp=sharing**) could be a potential workaround for Samsung devices but I don't possess a Samsung device so I'm not sure.

Could you please confirm if you see any differences? I might be able to borrow a Samsung device this weekend but until then I'm not sure if it works.

**Comment by Jarods-language-journey** [comment]
> 

I might be missing something here, but could clarify what you'd like me to try?

Thanks!

**Comment by lrorpilla** [comment]
@TheAtlasRises @Jarods-language-journey 
My bad, the hyperlink wasn't included. You can find the link **[here](https://drive.google.com/file/d/1MRqGP71PDGxeFtc_SQSJGahve4PUyv25/view?usp=sharing).**

**Comment by Jarods-language-journey** [comment]
Alrighty, the native selection options are back, so this works as an alternative. This suffices for my workflow, but I'll leave this open as I'm not seeing the jidoujisho pop-up. The pop-up was pretty handy in Chisa!

https://user-images.githubusercontent.com/80096108/190948974-eb9850e8-e678-4561-8b33-9bc8474c112b.mp4

**Comment by lrorpilla** [comment]
This is not the desired behaviour. It appears that Samsung devices do not correctly show the custom context menu. 

I am going to build another version that reverts the package that I use for the web view into the one for Chisa. Please let me know if that one works. Sorry for making you download different builds, it's just difficult because this is a manufacturer-specific issue.

**Comment by lrorpilla** [comment]
Hi @Jarods-language-journey, I have updated the link above and reverted it to a previous version using the WebView package version I used for Chisa.

**Comment by Jarods-language-journey** [comment]
Awesome, the build is back to how it was working in Chisa, giving the creator option back which is what I use quite a bit. It does have the both pop-ups, native and app-specific as shown in the screen record, but this also occurs in Chisa. Not a big deal to me, so if you wanna close it at that I'm all good here.


https://user-images.githubusercontent.com/80096108/190950602-0b6a3128-b549-4191-b178-9f9dee2d4070.mp4

**Comment by lrorpilla** [comment]
@Jarods-language-journey 
I'm going to try and investigate a custom fix for that double context menu issue for that package I use for Samsung devices experiencing this issue once I grab ahold and am able to borrow a Samsung device from family this weekend. Thanks for sticking with me.

**Comment by dkaknbk** [comment]
I also had the same issue with no pop-up whatsoever on my Lenovo Tablet, so it doesn't seem to be exclusive to Samsung devices However, installing the workaround build you posted above restored the expected behavior as it was on Chisa. I don't have the same issue with the double pop-ups.

**Comment by lrorpilla** [comment]
Hi, @Jarods-language-journey, 2.2.1 is out. I was wondering if you could test if this issue still persists?

**Comment by Jarods-language-journey** [comment]
> Hi, @Jarods-language-journey, 2.2.1 is out. I was wondering if you could test if this issue still persists?

Uninstalled and reinstalled the latest and the issue persists. If you want any testing, just lmk.

**Comment by lrorpilla** [comment]
2.2.0 has a different version of the WebView package that I use that is updated and probably has a lot of significant changes, but there were some problems with it so I rolled it back in 2.2.1 and 2.2.2. If you can try 2.2.0 and tell me how you go, that could help me determine if the version of the package I'm using has a problem.

**Comment by Jarods-language-journey** [comment]
> 2.2.0 has a different version of the WebView package that I use that is updated and probably has a lot of significant changes, but there were some problems with it so I rolled it back in 2.2.1 and 2.2.2. If you can try 2.2.0 and tell me how you go, that could help me determine if the version of the package I'm using has a problem.

Unfortunately, same issue on 2.2.0. The issue is the same as the video I had posted earlier in the thread where there are no pop ups.

**Comment by Jarods-language-journey** [comment]
> > 2.2.0 has a different version of the WebView package that I use that is updated and probably has a lot of significant changes, but there were some problems with it so I rolled it back in 2.2.1 and 2.2.2. If you can try 2.2.0 and tell me how you go, that could help me determine if the version of the package I'm using has a problem.
> 
> Unfortunately, same issue on 2.2.0. The issue is the same as the video I had posted earlier in the thread where there are no pop ups.

Correction, sorry looks like I swapped the apps. 2.2.0 is working with the jidoujisho pop up just fine.

**Comment by Jarods-language-journey** [comment]
> > > 2.2.0 has a different version of the WebView package that I use that is updated and probably has a lot of significant changes, but there were some problems with it so I rolled it back in 2.2.1 and 2.2.2. If you can try 2.2.0 and tell me how you go, that could help me determine if the version of the package I'm using has a problem.
> > 
> > 
> > Unfortunately, same issue on 2.2.0. The issue is the same as the video I had posted earlier in the thread where there are no pop ups.
> 
> Correction, sorry looks like I swapped the apps. 2.2.0 is working with the jidoujisho pop up just fine.

Sorry for the short successsion of responses, but I just found out an issue. It works when on paginated but doesn't work when on continuous (which is what I use). See the video attached

Uploading Screen_Recording_20230108_142336.mp4…

**Comment by lrorpilla** [comment]
Thanks @Jarods-language-journey, that information is what narrowed it down for me. I've fixed this in 2.2.3, seemed to be an issue in the backing WebView package which did not track `scrollX` for where to display the floating context menu. 

I included this custom fix in Chisa, but I seemed to have forgotten to include it as honestly, I've forgotten continuous layout exists since TTU released pagination. Please let me know how you go and if I may close this issue.

**Comment by Jarods-language-journey** [comment]
Updated and correct operation is restored :)! Since the issue is resolved, I will go ahead and close the thread now. Appreciate the work and response on the matter!
