### ISSUE TITLE
Forvo does not export to Anki

### ISSUE THREAD

**Issue by Jarods-language-journey** [lrorpilla/jidoujisho#123]
Android Version: 12
Phone: Galaxy S22 Ultra (latest Samsung update)
App version: Yuuna (jidoujisho_yuuna_2_0_0-arm64.apk)

Using the forvo field enhancement, upon trying to export cards to anki using forvo audio, nothing occurs. Upon switching over to Japanesepod (or the primary audio source), it exports immediately. No other fields were edited, this is directly from the reader. The screen capture exhibits this behavior below.

https://user-images.githubusercontent.com/80096108/190209427-e30f0ed5-69ae-4f43-8f0f-472c63c6caba.mp4

**Comment by lrorpilla** [comment]
I can confirm replicating and fixing this and this should be fixed in the next version.

**Comment by lrorpilla** [comment]
Hi Jarod, you can try and see if 2.0.2 has fixed this problem.

**Comment by Jarods-language-journey** [comment]
So it properly exports now and gives the message, but no card is created in Anki. This occurs with both audio sources.

https://user-images.githubusercontent.com/80096108/190273877-463d8296-0939-407c-b245-400b15d0f739.mp4

**Comment by lrorpilla** [comment]
Can I see the contents of your Standard profile?

**Comment by Jarods-language-journey** [comment]
![Screenshot_20220914-153750](https://user-images.githubusercontent.com/80096108/190275336-d4f427d6-d8e7-49f7-ae24-d9f4ee45ccd6.jpg)

**Comment by lrorpilla** [comment]
![Screenshot_20220915-083955](https://user-images.githubusercontent.com/11363922/190275446-e146b3c8-7d55-4bfd-9b58-9c8856413c29.png)
Hi @Jarods-language-journey,
This is the screen I am interested in. Select the Export profiles option from the main menu to find it.

**Comment by Jarods-language-journey** [comment]
It's looks like they're all empty. Putting in the correct fields solves the export issue

![Screenshot_20220914-154215](https://user-images.githubusercontent.com/80096108/190275690-1d3684f8-58cc-4d23-aeb0-d40f2395d4e2.jpg)
