### ISSUE TITLE
What dictionaries can I actually import?

### ISSUE THREAD

**Issue by Pr092m** [lrorpilla/jidoujisho#126]
No dic works, at least from here: https://mega.nz/folder/rIIHhAxb#d6GV9ZNTj9gUEaQtfGluqg

I'd like to use any J-J dic but none seem to work

**Comment by dstntwrldstgthr** [comment]
most of these work
https://learnjapanese.link/dictionaries

**Comment by lrorpilla** [comment]
You can use the Yomichan dictionaries in the link that you included. The app currently supports only Yomichan dictionaries, and you can find some on the Yomichan site or from the link above.
