### ISSUE TITLE
pronunciation pop-up

### ISSUE THREAD

**Issue by PhongTong** [lrorpilla/jidoujisho#127]
Can you add the pronunciation part into the pop-up dictionary? Just like Yomichan popup

**Comment by lrorpilla** [comment]
The app provides Furigana on top of your dictionary entries, and it also shows readings with pitch accent diagrams if you import a pitch dictionary.

If you want a specific UI change, I will need example images from other software or a concept to consider your request as I'm not sure what you want.

**Comment by PhongTong** [comment]
![image](https://user-images.githubusercontent.com/8979366/192919726-6286d752-cff0-4df5-8b6a-cd4ec16c4af8.png)
Something like this in Yomichan popup, click the icon and the audio will play
I just want to listen to native pronunciation and mimic them after. 
I think you can add it right beside the anki export button in your app pop-up
