### ISSUE TITLE
Chinese font bug 

### ISSUE THREAD

**Issue by Akitorubiaki** [lrorpilla/jidoujisho#128]
The font on the app is not a Japanese font but a Chinese font
Personal opinion but it can confuse people that start learning japanese and can't tell the difference between japanese font and chinese font.  For example:
![Screenshot_2022-10-06-14-34-31-90_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/115155692/194303269-680a3204-b798-40d0-a7ab-08fbd08e7c81.jpg)
And: 
![Screenshot_2022-10-06-14-34-08-38_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/115155692/194303345-947e5283-4ce1-4b63-84a1-132cba549b2f.jpg)

**Comment by lrorpilla** [comment]
Hi, I will address fixing this and implementing a fix for this as default behaviour or perhaps allow you to change the font at some point, only some devices are experiencing this issue, please see #125 in the meantime.

**Comment by baselmagdy2** [comment]
@lrorpilla I just wanted to note that the gdrive links are dead, could you please upload a fix? As I still have this issue

**Comment by lrorpilla** [comment]
This issue is resolved in **[2.1](https://github.com/lrorpilla/jidoujisho/releases/tag/2.1)** which forces the app to include and use Noto Sans JP regardless of locale. If you're still experiencing this issue, feel free to re-open.

Relevant issue #139.
