### ISSUE TITLE
Show images in dictionary

### ISSUE THREAD

**Issue by mathewthe2** [lrorpilla/jidoujisho#129]
There are image files in certain Yomichan dictionaries, but they are not displayed properly.

[More on dictionary image spec](https://github.com/FooSoft/yomichan/pull/446)

![image](https://user-images.githubusercontent.com/13146030/196406667-e23b6afe-ebf6-459d-b115-44feb9bbb9a3.png)

**Comment by lrorpilla** [comment]
Implemented in the [**2.9.0 preview**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.9.0-preview).
