### ISSUE TITLE
Audio lag/cut-off

### ISSUE THREAD

**Issue by trd-db** [lrorpilla/jidoujisho#130]
Currently on my device within the video player I am running into a weird issue. I have definition focus on, and after clicking on a subtitle the video pauses and the dictionary comes up. After dismissing the dictionary dialogue the audio will either be silent or it will start and then cut out. This can last for up to a second or two. It Doesn't always happen, but maybe about 60% of the time. I'm currently running this on the 2021 kindle fire 10.

**Comment by lrorpilla** [comment]
This is probably relevant to **#42** and **#17**, in which case it's really a matter of the VLC plugin I'm using being finicky with resuming.
