### ISSUE TITLE
[]Dictionary in Dictionary

### ISSUE THREAD

**Issue by JunkyardCat** [lrorpilla/jidoujisho#131]
so is there a way to scan a popped up dictionary term? i am gonna be using monolingual dictionary and was wondering if theres an easy way to also search the pop up meaning

this is similar to yomichans "Allow scanning popup content option"
```
Allow scanning popup content
Text inside of popups can be scanned for definitions, which will open a new popup.
```

**Comment by damiansh** [comment]
Well, you can select whatever term inside the description of the dictionary and press search. 

![Screenshot_20221123-211615](https://user-images.githubusercontent.com/44991000/203693280-9a910ee3-996a-4ef9-8aa9-4280b34b7203.jpg)

But, scanning like when you are reading or in the subs, it is not possible I think.

**Comment by JunkyardCat** [comment]
i see. thanks for the confirmation. hope you can incorporate that feature in the future but dont rush yourself :)

**Comment by lrorpilla** [comment]
Now that the dictionary search performance is a lot better since **[2.2](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2)**, I think I can improve on this front in the future but in the meantime, you may recursively search in dictionary definitions by selecting them as you would any other text.

**Comment by lrorpilla** [comment]
Just so people are aware, the current alternative to this is to double tap on a character in a dictionary definition. The text selection will change to the best word match and you can recursively search.

I believe having a full sized recursive dictionary page approach mitigates child popups from accidentally closing when you're multiple recursions in and I believe the readable text size being larger is beneficial on mobile. 

Regardless, I know this is still something people want but just to let people know, there is an alternative to child popups at the moment and that's how you use them. I might look into improving my approach in the future.

**Comment by lrorpilla** [comment]
I've decided to close this issue. Users can refer to [**this section**](https://github.com/lrorpilla/jidoujisho/wiki/7.-Tips-and-Tricks#recursive-look-ups) in the wiki for how to make recursive look-ups with this app.
