### ISSUE TITLE
Dictionaries not loading

### ISSUE THREAD

**Issue by VegasVed** [lrorpilla/jidoujisho#134]
I have tried loading two dictionaries (Yomichan zip formats), but nothing happens when I select them from the file picker. The file picker closes and the Import dialog remains open as if I never clicked on Import to select a file. 

Running Android 13 on an Oppo Find X5.

**Comment by VegasVed** [comment]
I have also tried running 2.1 but the issue remains.

**Comment by lrorpilla** [comment]
Hi, @VegasVed, could you please try the following version? Can you please try [this version](https://drive.google.com/file/d/135TT9xFnrjbFThoPJ-22QdFDBdN0uYxQ/view?usp=share_link)? You might need to uninstall to try and install the version.

**Comment by VegasVed** [comment]
This version worked! Thanks!

**Comment by lrorpilla** [comment]
**[2.2](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2)** is out which fixes a lot of dictionary import and search performance related issues. If you have any feedback or if you're still experiencing this issue, feel free to re-open.
