### ISSUE TITLE
Option for adding yt channel name/tv show series as a tag

### ISSUE THREAD

**Issue by sbstratos79** [lrorpilla/jidoujisho#137]
Immersive for mpv has a similar feature that auto assigns a series name based on the video title and exports it as an Anki tag. This is quite useful for filtering cards based on series name. 
Additionally, tags could be assigned for YouTube channels.

**Comment by lrorpilla** [comment]
May I ask, how would you like this to work? Would it be based on a folder name or should you be able to add and make your own selection of tags that you pick and are saved and pre-filled unless you change them?

It is possible for me to add an auto enhancement that adds the author/uploader or filename of currently playing but sourcing that information automatically is the tricky thing. I can make a way for a user to create and organize and set tags and make that an enhancement. I'll keep this open.

**Comment by sbstratos79** [comment]
Series tag should be automatically generated based on the filename. But the user should have the option to change/pre-configure series names. [Here's](https://github.com/Ben-Kerman/immersive/blob/master/doc/series.md) a document describing the `series` implementation in `Immersive` user-script for mpv. Maybe this can be useful as a reference for what kind of implementation I was hoping for.

**Comment by lrorpilla** [comment]
I've implemented a tags field in 2.5.13 which should fulfill this purpose. Users need to manually write and save space-delimited values that they want, and the tags value will persist across all cards made.

This isn't the spec above but it should do for users that binge watch or are reading a 9hr audiobook or so.
