### ISSUE TITLE
app using Chinese fonts even tho my phone is in Japanese 

### ISSUE THREAD

**Issue by baselmagdy2** [lrorpilla/jidoujisho#139]
![Screenshot_2023-01-01-13-01-10-84_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/80059946/210168358-a80702c0-3348-4e0b-8149-81afdd1846a1.jpg)

**Comment by lrorpilla** [comment]
Hi, I apologise. I know that you're still awaiting a fix for this issue, it just so happens that I was taking a break from active development and could not get to this as soon as possible. I will probably change the default font of the app to be a Japanese only font or add an option that will let you override to a Japanese only font.

**Comment by lrorpilla** [comment]
Hi, @baselmagdy2 , could you please try the following version? Can you please try [this version](https://drive.google.com/file/d/135TT9xFnrjbFThoPJ-22QdFDBdN0uYxQ/view?usp=share_link)? You might need to uninstall to try and install the version.

**Comment by baselmagdy2** [comment]
this fixed the issue , Thank you!!!

**Comment by lrorpilla** [comment]
It appears that I'll need to update this issue as it causes a white screen in place of the subtitles of the video. I will update a new app in the same link above in a moment.

**Comment by lrorpilla** [comment]
This issue is resolved in **https://github.com/lrorpilla/jidoujisho/releases/tag/2.1**, which forces the app to include and use Noto Sans JP regardless of locale. If you're still experiencing this issue, feel free to re-open.
