### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by cyra23** [lrorpilla/jidoujisho#144]
Hello, I've been trying to import a dsl dictionary that is 70mb and the app keeps crashing, is it possible to fix this? thank you

Version 2.3.5
Android 12

**Comment by lrorpilla** [comment]
Unfortunately, the bigger some DSL files are, this crash will occur. It probably has to do with the fact that the app needs to read everything to check if it's a UTF-16 or a UTF-8 file. Smaller DSL files are no problem but bigger ones will cause issues. I recommend importing Migaku dictionaries instead while this one isn't sorted out.

**Comment by lrorpilla** [comment]
Hi @cyra23, I've released a hotfix for 2.3.6 which changes the method that the app uses to detect what charset a DSL file is. The app may freeze sometimes while the encoding is being detected, but I've tested it on dictionaries as huge as 120MB and I experience no crashes now. Feel free to ask this to be re-opened if you're having any trouble.
