### ISSUE TITLE
card creator using all dictionaries instead of top dictionary only 

### ISSUE THREAD

**Issue by baselmagdy2** [lrorpilla/jidoujisho#145]
For some reason no matter of I set the one I want to use to hidden then use hidden meaning option or collapse all then use expanded meaning option or vice versa it's always using all dictionaries instead of my top dictionary 
![Screenshot_2023-01-21-02-39-43-93_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/80059946/213829935-97a8312a-6a5c-46c6-a314-123d4475a369.jpg)

**Comment by lrorpilla** [comment]
You need to edit the active fields and remove the Meaning field and replace it with whichever fields you want active, Expanded, Collapsed, etc.

Note that the expanded and collapsed dictionaries refer to the ones that are expanded and collapsed in the dictionary menu, not the currently expanded or collapsed before you hit create.

**Comment by lrorpilla** [comment]
![Screenshot_20230121-122513](https://user-images.githubusercontent.com/11363922/213839859-1803a0ea-d47b-48ac-9bd7-4e478c516481.png)
![Screenshot_20230121-122538](https://user-images.githubusercontent.com/11363922/213839860-38d75413-b23f-41ad-bf52-cd10e2be1f70.png)

**Comment by Skyroniz** [comment]
Sorry for my english in advance, I'm French.  I have an idea to just select one meaning ( or  a piece of meaning) in any dictionary. We can just simply use the Stash by selecting the meaning in any dictionary. To do so, I use "pop from stash" as an automatic enhancement of notes. 

 In this way:
![Screenshot_2023-01-23-12-39-22-24_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/59112988/214034594-91a2e8ed-e524-4f18-9437-2f3d27f16344.jpg)
So, with that ,  edit the Meaning field and replace  with Notes field. 
Like that: 
![Screenshot_2023-01-23-13-15-40-65_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/59112988/214038402-e3f2d981-54b5-4433-89ce-953a29d64e18.jpg)

**Comment by Skyroniz** [comment]
https://user-images.githubusercontent.com/59112988/214059497-d28b542b-99ba-4dff-a49e-5dfec3a62713.mp4

**Comment by lrorpilla** [comment]
The latest 2.5 preview now allows users to pick a single dictionary for card export, with a new button beside each dictionary entry.
