### ISSUE TITLE
E-Book English learners

### ISSUE THREAD

**Issue by vczEz** [lrorpilla/jidoujisho#148]
It doesn't work, my book is EPUB format. I use the version 2.3.7
![photo_2023-01-21_18-47-15](https://user-images.githubusercontent.com/78620977/213896048-20942ade-6884-46e9-9b6b-761911993ab1.jpg)

**Comment by vczEz** [comment]
How can I download dictionary for English to Spanish?

**Comment by lrorpilla** [comment]
You will need to source dictionaries in DSL or Migaku archive format. You can find some [here](https://mega.nz/folder/BVZDzSqQ#52DxuFK0csXuBu-DVK86fQ/folder/gABRXYzL)  and find others if you ask around in the community. 

You can share your EPUB file with me and I'll test it out but if it loads, the reader component isn't my jurisdiction so I can't fix it if your particular file doesn't work (I've tested a variety of English and Japanese books, on Library Genesis and some classics I've found online in EPUB format).

**Comment by vczEz** [comment]
https://www.mediafire.com/folder/fuimks05zrpe8/books

Maybe it's the book in the application. Man your application is awesome bro!!, I think it is superior that Migaku and ejoy and mpvacious.


![photo_2023-01-21_22-15-00](https://user-images.githubusercontent.com/78620977/213900288-c6746775-3e51-4cac-a782-21d533071e3a.jpg)

![photo_2023-01-21_22-15-03](https://user-images.githubusercontent.com/78620977/213900293-352745a3-b9e9-4f40-a8b3-f1b39a0c1943.jpg)

**Comment by vczEz** [comment]
And is it normal that the background is white, and my selected theme is black?
![photo_2023-01-21_22-20-05](https://user-images.githubusercontent.com/78620977/213900506-e839fb43-8aea-4f5e-a79c-583daa21a97e.jpg)

**Comment by lrorpilla** [comment]
It is normal, yeah. The reader is a separate web application that is bundled with my app, so you will need to change the theme from within the reader settings.

**Comment by lrorpilla** [comment]
I will probably change the color of the pop-up in the reader to depend on the color of the current reader theme at some point.

**Comment by lrorpilla** [comment]
It's been a while but just want to let you know since 2.4.3 that the color of the pop-up and recursive searches within the Reader now adapts to the reader theme.
