### ISSUE TITLE
Copy pop-up doesn't copy

### ISSUE THREAD

**Issue by Jarods-language-journey** [lrorpilla/jidoujisho#149]
Heyo, back again. This time the pop-up does not actually copy anything to my clipboard, see the video attached. 

Device: Samsung Galaxy S22 Ultra
Android version: latest
Jidouversion: 2.2.4

https://user-images.githubusercontent.com/80096108/214420084-1e56d15a-b065-46a3-8268-b62291edddb6.mp4

My workaround is to open it up in card export and copy the sentence from there or open things up in Chisa.

Let me know if you need anything else.

**Comment by lrorpilla** [comment]
Hi Jarod, this is fixed in 2.2.5 and is in the patch notes. 

`Fixed an issue where copying in the Reader WebView would result in no text being copied.`

The latest version is 2.3.7.

**Comment by Jarods-language-journey** [comment]
Man I'm a whole year behind 😂, thanks man.
