### ISSUE TITLE
Filters option

### ISSUE THREAD

**Issue by Hexavall** [lrorpilla/jidoujisho#16]
May be good to have a filters option while searching content. 
Some examples are:
-Close captioning available videos
-Videos
-Channels
-Songs
-Newer/Older
And others like those

Thanks for your work!

**Comment by lrorpilla** [comment]
This application doesn't use the YouTube API, it uses a library that loads the website and then attempts to simulate searching for content and then it father's the data yielded from that.

Closed captioning available videos: This is possible, but it will return videos that have a closed caption for any language and not specifically Japanese. I'm sure if you are making a Japanese related search query it will still be useful.
Videos: Trivially, you are already searching only for videos so this is already the case.
Channels: Not possible, I believe. The search method I'm using can't really filter searching only for channels.
Songs: Not technically possible, I wouldn't know how to identify a video with this.
Newer/Older: Search only returns a few elements, so I don't think this is very useful. What I can do is do newer/older for channel videos.

**Comment by lrorpilla** [comment]
I added what I could implement back in [0.14](https://github.com/lrorpilla/jidoujisho/releases/tag/0.14.2-beta), see the following release notes:
* Added an option to view channel videos by oldest or latest when holding a channel in the Channels page (#16)

For the filters that I could not implement, my alternative solution that I implemented in 0.15:
* **(New Feature) Share Intent** - **YouTube links can now be shared to the application to open a video** (#18), photos and text can now be shared to the application for the card creator

Users can search with the YouTube app and find whatever they need using the YouTube app's extensive filter options and then very easily share a video to the app to load it. I believe this should just as intuitively fulfill this request, so I'm closing this issue.
