### ISSUE TITLE
Making flashcards 

### ISSUE THREAD

**Issue by FahadHeiji** [lrorpilla/jidoujisho#160]
You have built a great app that has all the features a language learner could need, keep it up legend 

The problem is i can't make anki flashcards before it was working smoothly but no, i tried :

- New profiles.

 - Install different versions of Ankidroid with different versions of Jidoujisho.
 
Nothing changed, i hope you can help me.
![Screenshot_2023-03-04-09-22-44-76_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/114103612/223100445-80477241-f992-4246-a48a-9ea16be0a25a.jpg)

**Comment by lrorpilla** [comment]
Are you certain that this is the same device with a different version? What was the last working version you were using?

**Comment by lrorpilla** [comment]
Did you upgrade Android versions recently? What is the make and model of your device? Have you granted the app its appropriate storage permissions?
The only change that I see is that I moved the directory I store temporary media to export to AnkiDroid to using a public Pictures directory instead of a directory within the app's internal directory.

Can you try downloading the latest 2.4 Preview 10 and try it out? I've changed the directory to DCIM.
If it still doesn't work, I will see what I can do.

**Comment by FahadHeiji** [comment]
Unfortunately the problem still exists
 
Yes it's the same device , and I didn't update the Android version it's still the same.

 version 2.3 was working for me i reinstall/redownload it  even I upgraded to 2.4 but nothing changed, i also tried versions 2.2, 2.0, 1.1 

I did all the permissions for both Jidoujisho & Anki but didn't work.


https://user-images.githubusercontent.com/114103612/223195332-7cf5d830-d893-4764-bdb5-9ae81f9c4e39.mp4

**Comment by lrorpilla** [comment]
I think I've identified the change between 2.3 and 2.4 that caused this. When I get the time tomorrow, I'll see if I can reproduce the 2.3 behaviour. I'll build the fix though I'll need you to test the fix as I don't have a device that can reproduce the issue.

**Comment by lrorpilla** [comment]
In the meantime, can you please provide your Android device and phone details so I can know which manufacturer's users might be experiencing this issue?

**Comment by FahadHeiji** [comment]
I'll at your command.

Here is my device info 
![Uploading Screenshot_2023-03-06-20-26-51-91_fc704e6b13c4fb26bf5e411f75da84f2.jpg…]()

**Comment by FahadHeiji** [comment]
![Screenshot_2023-03-06-20-26-51-91_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/114103612/223199005-d939f2a8-a8ad-4650-8d96-d047865eaebe.jpg)

I'll be at your command.

Here is my device info

**Comment by lrorpilla** [comment]
Hi @FahadHeiji, **[I uploaded a custom build to Google Drive](https://drive.google.com/file/d/1AWCph7yN2d3IGTYn-Igomrf5ZQlJawSI/view?usp=share_link)**. Can you please try and tell me if it works for you? I still need to investigate if the fix I suspect works, so please let me know how you go.

**Comment by FahadHeiji** [comment]
Alright I'll send the request

**Comment by lrorpilla** [comment]
Forgot to make the link public, try again.

**Comment by FahadHeiji** [comment]
Finally, It's working again
Thanks to you legend now my SM will getting better.

https://user-images.githubusercontent.com/114103612/223418596-11317688-13ec-4de8-9314-0848b66e2068.mp4

**Comment by lrorpilla** [comment]
Yeah, I'll see if I can include this fix in a proper preview, thanks for reporting back.

**Comment by lrorpilla** [comment]
Hi, just want to let you know that 2.4 Preview 13 fixes a lot, but I've also included the fix that I employed for your custom build in it.

Could you please give it a shot and let me know if it works for you?
