### ISSUE TITLE
Dictionary name included in meaning

### ISSUE THREAD

**Issue by betaredex** [lrorpilla/jidoujisho#163]
Whenever I instant export a card to anki, 【JMdict (English)】 appears above the meaning in the meaning field. I'd like to use instant export instead of manually deleting this every time. Is there a way to accomplish this?

**Comment by lrorpilla** [comment]
There's an option called "Prepend dictionary names in meaning" when editing your current export profile which allows you to toggle this.

**Comment by betaredex** [comment]
Awesome, thanks.
