### ISSUE TITLE
Tap-to-Hide Dict. Not Working 

### ISSUE THREAD

**Issue by JarodMica** [lrorpilla/jidoujisho#164]
**Version: 2.4.3**
**Phone: S22 Ultra**

Hey there, a small little bug on the latest version where if you unselect "Highlight text on tap", the definition will not hide itself on tapping it again. It works when it's toggled on, just not when it's off. 

Another unrelated thing, but any way to have an option for the dict. pop up color to be black on a tan background? I prefer tan while reading, but I'd prefer black for the definition background.

Good work though, loving the continue support for the app. Let me know if you have any questions.

**Comment by JarodMica** [comment]
Makes sense then! I'll be reading with it now on lol.  Thanks for the acknowledgement, appreciate it!

**Comment by lrorpilla** [comment]
Hey, @JarodMica. Just want to let you know that the latest preview of **[the 2.5 preview](https://github.com/lrorpilla/jidoujisho/releases/tag/2.5-preview)** has a new option which allows the dictionary popup to not adapt to the Reader WebView's theme.

**Comment by JarodMica** [comment]
Ah shoot, I'll have to try it out!  Saw that you wrapped in openAI as well so this is getting interesting!  Thanks for replying!
