### ISSUE TITLE
Version 2.4 Update Freezes on Launch

### ISSUE THREAD

**Issue by ukw16** [lrorpilla/jidoujisho#165]
Huawei P30
Emui Android 12.0.0.134 (latest) 
51GB out of 110GB Free space

Good day, love the app to bits. It's the perfect immersion tool. I wanted to report an issue that I'm experiencing. Can't seem to use the app after installing it as it freezes on the splash screen. 

Here's a video of me installing it: https://streamable.com/0884je 

Installed arm64 apk but as you can see in the vid it freezes. Left in or for five minutes and still freezes. Tried to install the other package but it doesn't completely install.

Kindly asking for your help. If push comes to shove I'll just fresh install which does suck though. Gonna lose all my cards, books, etc.

**Comment by lrorpilla** [comment]
What's your history of usage with the app? Did you upgrade from a previous version, install some dictionaries recently or make some searches?

Unfortunately I think you'll have to do a fresh install but you won't lose any cards you've made, but you will have to reimport books unfortunately.

**Comment by ukw16** [comment]
> What's your history of usage with the app? Did you upgrade from a previous version, install some dictionaries recently or make some searches?
> 
> Unfortunately I think you'll have to do a fresh install but you won't lose any cards you've made, but you will have to reimport books unfortunately.

I'm upgrading from a previous version. I didn't install any dictionaries. I made searches before the installation though but since I can't now, no new searches. 

But I'll fresh install and see what happens. Thanks alot.

**Comment by lrorpilla** [comment]
Which version? As 2.4's release notes states, the new schema requires a fresh installation.

**Comment by ukw16** [comment]
Yeah, it's 2.4. I see, looks like I just missed that.

**Comment by lrorpilla** [comment]
If you upgraded from a pre-2.4 version to 2.4 version, that's where you might see a problem like you've shown when launching the app, that's why I was asking for what version you might have upgraded from (i.e. 2.3 or something else).

**Comment by ukw16** [comment]
I see. Fresh installed and everything works fine. Thanks for the help.
