### ISSUE TITLE
Random Crashes on certain words look up

### ISSUE THREAD

**Issue by Shudhanshu-Raj** [lrorpilla/jidoujisho#168]
I can't find the logs too, Can you help me pls?

**Comment by lrorpilla** [comment]
I appreciate the report but I need more information to action this issue. Please give details about your device. It would be best if you could give instructions on how you might reproduce this issue or if you can demonstrate it occurring with a recording, as well as what you were doing or searching at the time.

**Comment by Shudhanshu-Raj** [comment]
My device is Motorola e40,
I tried reproducing the cras multiple times but I Can't seem to do it, When it happened tho, it was always katakana words which were causing problems

**Comment by Shudhanshu-Raj** [comment]
I'll try different ways on reproducing it later when I'm free

**Comment by lrorpilla** [comment]
It would be useful if you could give the specific search terms you were searching, or provide the same media for me to test with.

**Comment by lrorpilla** [comment]
@Shudhanshu-Raj Any updates?

**Comment by Shudhanshu-Raj** [comment]
The crash has stopped happening, I don't know how but I think it had
something to with certain words I guess anyways if it happens again, I'll
try getting my more info and let you know, Thanks

**Comment by lrorpilla** [comment]
I fixed the above issue in 2.5.4. I'm not sure if it's the same issue that's affecting you but I've addressed a fatal crash regarding certain search terms regardless.

If this issue doesn't recur, I'll probably close this thread.
