### ISSUE TITLE
Add option to copy or export sentences from mokuro reader

### ISSUE THREAD

**Issue by TriDyE** [lrorpilla/jidoujisho#173]
Good afternoon:

When I'm reading manga using the mokuro reader, sometimes I need to translate the full sentence or part of the text, not only to find up a single word using the dictionary built in this app.

Using PC, I just copy the sentence and paste it on DeepL or G-Translate. But using this app, I need to select a word to show up the dictionary, click in the button to show the creation card menu and from there copy the full sentence and paste on online translators or other apps to translate. A lot of effort for just a simple task on PC.

From Android + kiwibrowser + mokuro, I can select the full sentence and in the menu that emerges after selecting, share it to DeepL app and it automatly translates the sentence.

Please, can you add the possibilty to select sentences or part of the text and share/export/copy to other apps like DeepL, clipboard, etc? Just like the video player where you can share a full subtitle to other app or copy onto clipboard using few screen touches.

Thanks for all your effort!!

**Comment by lrorpilla** [comment]
As you wish, the context menu is now available for the Mokuro reader source -- and sharing is now available app-wide to most selectable elements in the application. Let me know if you have any extra issues regarding this issue.

**Comment by lrorpilla** [comment]
Will quickly reupload the version in a while.

**Comment by lrorpilla** [comment]
Reuploaded -- I hotfixed an issue where the Creator context menu option didn't include the image.
