### ISSUE TITLE
Add dark mode in Mokuro reader

### ISSUE THREAD

**Issue by TriDyE** [lrorpilla/jidoujisho#175]
Good afternoon;

I don't know if this is even possible, but I'll try.

When I was using KiwiBrowser + Mokuro + Yomichan in my Android phone (a lot of apps and work until I found your application), I installed an extension called "dark reader" that modify the way that Mokuro reader shows the menu and background, as the image below shows.

![image](https://user-images.githubusercontent.com/102191690/231817526-3481a960-b278-4f86-8498-ee23283a37a9.png)

Is it possible to add a "dark mode" into Jidoujisho for the Mokuro reader?

Thanks for your work!!

**Comment by lrorpilla** [comment]
This option is added in 2.5.6. Note that this needs to be toggled on as dark theme injection is off by default.
