### ISSUE TITLE
Dictionary doesn't work in the reader

### ISSUE THREAD

**Issue by ncuh** [lrorpilla/jidoujisho#177]
Hi. Description:
I change the target language to English, open an English book. I have 2 dictionaries. En-en and en-ru. En-en is working and en-ru doesn't. If I click on a word and then click search - it shows both.
![IMG_20230419_005659](https://user-images.githubusercontent.com/13517548/232834711-57636429-3b98-4b9a-8684-993886f3fd13.jpg)
![IMG_20230419_005719](https://user-images.githubusercontent.com/13517548/232834702-556718f1-1ca4-4bb7-920c-351a5c38f1c5.jpg)

**Comment by lrorpilla** [comment]
Perhaps the dictionary is collapsed? Please share your dictionary menu and if you can, the dictionary file.

**Comment by lrorpilla** [comment]
Please also give more information about your device and app version.

**Comment by lrorpilla** [comment]
By the way, I've reuploaded 2.5.10 right now to fix the overflow issue you've shown above where text is too long.

**Comment by ncuh** [comment]
Hi. It's not collapsed. 
2.5.9 and 2.5.10 same issue.
Realme x2pro Android 11.
![Screenshot_2023-04-19-18-52-07-87_d1e85489dfcf960faafc2f4d5db41573](https://user-images.githubusercontent.com/13517548/233041276-4ab33c51-8ef3-4eb3-a8a7-75c6820eefd2.jpg)

https://disk.yandex.ru/d/w7SoErTj3Nk8Af

**Comment by lrorpilla** [comment]
I'm not sure how you've managed to import that Russian dictionary as I've tried to import it as DSL and it just crashes.

**Comment by ncuh** [comment]
> I'm not sure how you've managed to import that Russian dictionary as I've tried to import it as DSL and it just crashes.

Huh, no idea. Did you try to import the file called "En-Ru-Apresyan.dsl.dz", right?

**Comment by lrorpilla** [comment]
Hi @ncuh, I've reuploaded 2.5.10 with some changes. Can you please clear all your dictionary data and try importing everything you have again?
