### ISSUE TITLE
Feature request: Look up words in subtitle list mode

### ISSUE THREAD

**Issue by helica1** [lrorpilla/jidoujisho#179]
First of all, thank you so much for your work on this app. It is my main "immersion" app - mostly reading books.

I have a feature request: to be able to look up words while in subtitle "list" mode (swipe down when watching a video). 

I often watch videos in this mode because I like to focus on the words rather than the video. 

This would be especially useful for audiobooks with transcripts synced to subtitles.

Thank you for considering!

**Comment by lrorpilla** [comment]
Hi @helica1, I've implemented this in 2.5.11.

You should be able to get an appropriate image and audio for the user hovered or selected subtitle.
Let me know if this implementation is satisfactory enough for your use case. Thanks for your request and use.

**Comment by lrorpilla** [comment]
I've reuploaded 2.5.11 with some fixes.

**Comment by helica1** [comment]
Wow, this change is fantastic - thank you for getting it done so quickly!

I do have one small additional request (hate to ask, but I spend 2-3 hours
a day in this amazing app for what it's worth...):
When in subtitle list mode, could you consider adding a toggle switch or a
preference to NOT automatically return to the video when a subtitle is
played or selected? In other words, it would be perfect to have the sound
of the video play while remaining on the subtitle list screen. Or perhaps
the video plays in the background in 5% opacity or something. For many
types of videos (audiobooks with subtitles, monologues, podcasts, etc) it
is not necessary to see the video.

I am imagining an environment where one can do the vast majority of their
immersion from the subtitle list screen.

For instance, there is a growing community on TMW discord server where
Kanjieater developed some scripts to align the epub with the audiobook
using whisper (
https://discord.com/channels/617136488840429598/1078829614060802200). There
is not an optimal way to view these subtitled audiobooks on mobile at the
moment - and I think that this subtitle list mode would be ideal with this
one small suggested change. Thank you so much for considering!

**Comment by lrorpilla** [comment]
Hi @helica1. I have reuploaded 2.5.11 with a new button that allows you to reveal a play/pause button, as well as modified the behavior when this mode is on to allow seeking instead of closing the transcript. It will also automatically pause on tap to select and will resume on clear or swipe away. Let me know how this works for your purposes.

**Comment by lrorpilla** [comment]
Re-uploaded again.

**Comment by helica1** [comment]
Wow, this is absolutely perfect. Incredible! I think this would be a very
good study method for reviewing a video after watching it to see if a word
"deserves" to be added to Anki, as well as for reading subtitled
audiobooks. Thank you so much!

**Comment by lrorpilla** [comment]
Glad to hear you're finding it useful -- I thought it was essential for me to implement when I read your suggestion so I got to it quickly.

Just want to let you know 2.5.12 allows you to toggle the video's visibility.
