### ISSUE TITLE
Add "share to/open with jidoujisho"

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#18]
In YouTube, the search is actually pretty good, so I like to use it for most videos. But occasionally something comes up with subs and I'd like to watch that in jidoujisho just because it's convenient.

It would be nice to have an option to open the current youtube video in jidoujisho for this reason.

**Comment by lrorpilla** [comment]
Yeah, this is a feature I intend to add.

**Comment by lrorpilla** [comment]
I have implemented this feature in [0.15.0](https://github.com/lrorpilla/jidoujisho/releases/tag/0.15.0-beta).

See the relevant line in the release notes:
* **(New Feature) Share Intent** - **YouTube links can now be shared to the application to open a video**, photos and text can now be shared to the application for the card creator

With that, I am closing this issue.
