### ISSUE TITLE
[Feature Request]Export secondary subtitles in the same card

### ISSUE THREAD

**Issue by Vonmusel** [lrorpilla/jidoujisho#180]
Export secondary subtitles in the same card: If you have english subtitles you can add a translation to your cards. Thanks

**Comment by lrorpilla** [comment]
Hi @Vonmusel, please see #42 and #93.

I don't plan to support any workflow or make it any easier for users to have a context from their native language.

I'm not against pull requests for features like this but I personally discourage this kind of workflow so I unfortunately will not develop for it over other features that I find are essential to learners.

**Comment by Vonmusel** [comment]
Although with your app i can understand the meaning of the single word i can't understand the meaning of the whole sentence.  So it looks like your app is mostly for intermediate-advanced learners.

**Comment by lrorpilla** [comment]
That's correct. I have made the decision pretty early in development that my philosophy in making and introducing features to the app will be to prevent users from performing what are certainly some pitfall behaviours that would hinder their progress with their target language by omitting certain features that they may rely on as a crutch.

I am aware that as a result, I will have a niche audience in making these decisions, but to be frank, there is no shortage of apps for beginner Japanese.
