### ISSUE TITLE
Creating cards in the mokuro reader occasionally uses the incorrect image

### ISSUE THREAD

**Issue by ZXY101** [lrorpilla/jidoujisho#188]
### Description:
When using the mokuro reader and creating cards, sometimes it will stop updating the image. This happens randomly when I create multiple cards in a row. I haven't been able to reliably recreate the issue, sometimes it works perfectly and I can make several cards in a row and other times I can only make one or two cards before the image stops updating. Clearing all the fields or closing the manga doesn't seem to resolve the issue, only completely closing the app fixes it.

### Specifications:
- App version: 2.6.0 (It also occurred on earlier versions)
- Device: Samsung Galaxy Note10 Lite (Android 13)

### Video

https://user-images.githubusercontent.com/39561296/235505255-b0a135df-619f-49ca-8d15-d31866360d00.mp4

**Comment by lrorpilla** [comment]
Hi @ZXY101, thanks for the report. I think I know the cause of the issue. Are you reading locally or are these online images?

**Comment by lrorpilla** [comment]
I'll just reach out to you privately and send you a candidate fix for this issue. Can you please try to see if you can't re-create the issue on it?

**Comment by ZXY101** [comment]
Resolved in #189
