### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Shudhanshu-Raj** [lrorpilla/jidoujisho#190]
It's not exactly a bug but it's very important, Exporting cards either through instant export or manual should automatically dismiss duplicates otherwise it would cause a serious inconvenience later on, Hence I would be thankful if you add it, 

Regards

**Comment by lrorpilla** [comment]
There are duplicate checks but it is [limited by an AnkiDroid issue](https://github.com/ankidroid/Anki-Android/issues/13561), the API implementation by this app is correct afaik.

Not sure what you mean by dismissing but when your icon is red, you can just choose not to export.

**Comment by Shudhanshu-Raj** [comment]
when is the icon red ?

**Comment by lrorpilla** [comment]
Please read the [2.5 release notes](https://github.com/lrorpilla/jidoujisho/releases/tag/2.5):
>### 🎴 Duplicate Checks
>- **Existing users will need to set their template that they want to check duplicates for (the Term or Word field) as the first field of their card type for this to function.** For users that use the app's provided card type, You may do this via the `Manage note types` option in AnkiDroid and swapping the `Term` and `Sentence` fields in place. New users will have an updated default card type and template, and no change is necessary from this version onwards.
>- The app will now show a red icon for the Card Creator and Instant Export quick actions if there are notes in AnkiDroid with the currently selected card type that are found to have the same first field value as a dictionary entry's Term.
>- This works on recently exported cards or cards that have been exported with the app after the user has installed this version.

**Comment by Shudhanshu-Raj** [comment]
I'll look into it also is automatic frequency to cards possible?

**Comment by lrorpilla** [comment]
The wiki is not complete, but there is [**a relevant answer**](https://github.com/lrorpilla/jidoujisho/wiki/1.-FAQ#i-have-this-specific-feature-on-my-workflow-will-you-implement-it).

**Comment by Shudhanshu-Raj** [comment]
I'm sorry but some buttons from #5 and #6 don't work and don't show up any content when clicked? Can you pls help me?

**Comment by lrorpilla** [comment]
Hi @Shudhanshu-Raj, as I mentioned, the wiki is not complete.

**Comment by Shudhanshu-Raj** [comment]
I see, In release note of 2.5 you mention "Manage note type in Ankidroid wnd swap the term and sentence field" but that option I think isn't available on ankidroid? If it is, can you help me?

**Comment by lrorpilla** [comment]
You can find it in the upper-right menu with AnkiDroid under `Manage note types` or `ノートタイプを管理`.

**Comment by Shudhanshu-Raj** [comment]
Omg, It feels like I've just unlocked a new power, thanks so much

**Comment by Shudhanshu-Raj** [comment]
I forgot this but sometimes the sentence doesn't export but other times they do, I can't even find a pattern for it

**Comment by lrorpilla** [comment]
Glad to help 🙂
I'm hoping to get the limitations on duplicate checks resolved but I will have to get ahold of the AnkiDroid team for what's going on with the issue I have linked above.

If there's anything else I can help with, you can mention it below.

**Comment by Shudhanshu-Raj** [comment]
> I forgot this but sometimes the sentence doesn't export but other times they do, I can't even find a pattern for it

Can you read this once?

**Comment by lrorpilla** [comment]
What version are you using?

**Comment by lrorpilla** [comment]
If you can demonstrate your issue with a video recording or a screenshot, I can answer your question.

**Comment by Shudhanshu-Raj** [comment]
![Screenshot_20230503-094443](https://user-images.githubusercontent.com/76690780/235831880-83e766a1-e2fd-4e4c-9490-aacf797ea740.png)
I can't see the red dot?

**Comment by lrorpilla** [comment]
Was the word for this card exported recently or after installation of a post 2.5 version?

> This works on recently exported cards or cards that have been exported with the app after the user has installed this version.

What version are you using?

**Comment by Shudhanshu-Raj** [comment]
2.6.1

**Comment by Shudhanshu-Raj** [comment]
It was exported yesterday

**Comment by Shudhanshu-Raj** [comment]
Yesterday the version was 2.5.1

**Comment by lrorpilla** [comment]
If you export cards from now on, and you have set your term field as the first field, you should get a red icon on your Instant Export or Card Creator quick action buttons.

However,
> There are duplicate checks but it is [**limited by an AnkiDroid issue**](https://github.com/ankidroid/Anki-Android/issues/13561), the API implementation by this app is correct afaik.

**Comment by Shudhanshu-Raj** [comment]
I see thanks

**Comment by Shudhanshu-Raj** [comment]
Lastly, can you tell me how can I change my default export note type?

**Comment by lrorpilla** [comment]
You can go to `Export profiles` under the upper right menu button in my app or you can look at Anki documentation to learn how to customise my app's card type.
