### ISSUE TITLE
Context-aware lookups with ChatGPT

### ISSUE THREAD

**Issue by phly95** [lrorpilla/jidoujisho#207]
Sometimes words have many definitions and the context determines which to use. For example:

くむ【組む】
〘v5m〙
1 to cross (legs or arms); to link (arms).
2 to put together; to construct; to assemble; to produce (e.g. TV program).
3 to braid; to plait.
4 to grapple; to wrestle.
5 to unite; to join; to link up; to form an alliance.
6 to set (e.g. type).
7 to issue (e.g. money order).

ChatGPT can get a context aware definition for words by either generating it itself or if it's fed a list of definitions (like above) select the most relevant one, potentially providing an explanation with it. 

This can also help with words that are not in a dictionary, since chatGPT has general knowledge outside the dictionary.

Additionally, for really difficult sentences, you could also have it break down and explain the whole sentence.

**Comment by lrorpilla** [comment]
Not going to implement this as I believe it's the learner's responsibility to distinguish which definition is being used, and I think this is out of scope for my personal vision with the ChatGPT support for this app.
