### ISSUE TITLE
Card duplicates

### ISSUE THREAD

**Issue by cyra23** [lrorpilla/jidoujisho#211]
Hello, I'm using version 2.7.0 and it does not detect duplicates anymore unless the same card type is used. I remember that using the same type was not necessary, the cards just had to be in the same deck

**Comment by cyra23** [comment]
thank you for your amazing work!

**Comment by lrorpilla** [comment]
I've re-released **[2.7.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.7.0)** just now -- please note the duplicate checks now happen for every first field of every card type. The duplicate checks actually aren't constrained to a deck -- there is no way to do so, so if you are using premades, you might need to reorder their first fields for convenience.

If there are any issues, feel free to ask.
