### ISSUE TITLE
Html reader bug?

### ISSUE THREAD

**Issue by ChubYee** [lrorpilla/jidoujisho#213]
When I use kiwi browser to read Mokuro manga, it keeps the zoom level, but for some reason with jidoujisho, it resets back to default when a page is turned. I'm using version 2.7

https://github.com/lrorpilla/jidoujisho/assets/104586776/d3879d07-9570-4d23-8d68-7f15a75984b8

**Comment by lrorpilla** [comment]
This is intended behaviour unfortunately. I can't remember off the top of my head but this is a workaround to make saving work. I will keep this issue open in case I find a solution.

**Comment by lrorpilla** [comment]
I've re-released [**2.7.0]**(https://github.com/lrorpilla/jidoujisho/releases/tag/2.7.0) to hotfix this.
