### ISSUE TITLE
Configure subtitle font size

### ISSUE THREAD

**Issue by michinoke** [lrorpilla/jidoujisho#22]
I'm using a Galaxy Tab S6 Lite (2000 x 1200px) and I find the size of the subtitles too small to read comfortably.

It seems to be hardcoded to 16px atm, would it be possible to make it configurable?

![Screenshot_20210625-131429](https://user-images.githubusercontent.com/46501392/123365063-e2c21100-d5b8-11eb-9973-5d1085feed59.jpg)

**Comment by lrorpilla** [comment]
I'm actually in a little break right now so I'm not implementing any new features so this won't be in a new public release I'll drop, but if it's just the subtitle size you want changed I can compile and prepare a custom APK for you real quick.

For proper app-wide text scaling, I'll have that done once I've rested and had a break, sorry for the wait.

**Comment by lrorpilla** [comment]
I've uploaded that quick build [here](https://drive.google.com/drive/folders/1FKR9WZHktJ8I8Tgj6f74O4d5vyq3xccr), let me know if the new text size is a bit too much, I just doubled it from 24px to 48px. I'll have more formal accessibility and text settings in the next major release.

**Comment by michinoke** [comment]
Thanks, did you mean to link to a private folder though rather than a shared file? Requires sign-in and an access request.

**Comment by lrorpilla** [comment]
Yeah, my bad. That's my oversight. Didn't set the folder to share to anyone with the link. It should be set now.

**Comment by lrorpilla** [comment]
Forgot to respond to this, I have addressed this issue in [**0.23**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.23.2-beta), there should now be an option under `Subtitle Timing and Appearance` that will allow you to set the font size. May later on, I'll allow styling of the text but for now I believe this should suffice.
