### ISSUE TITLE
Scrolling gets stuck on pop-up

### ISSUE THREAD

**Issue by amazingstar6** [lrorpilla/jidoujisho#224]
Hii, when I open a pop-up definition when watching a video through the subtitles, it somehow gets stuck when I try to scroll for a few seconds. I tried to show it in the video here: https://drive.google.com/file/d/1MIROZMuXTXWY075A7ekExBYlgEEj4VFl/view?usp=sharing
I'm running the latest version of the app.

**Comment by lrorpilla** [comment]
How many cards do you have in Anki across all decks and card types? This may be due to changes in duplicate checks.

What device are you using? I can't replicate this issue on my new and old phone.

**Comment by amazingstar6** [comment]
I have 72425 cards in total, around 100 of them are the old jidoujisho card type and around 30 use the new format. If the check duplicates goes over every card each time then the lag would make sense.

I'm using a samsung galaxy 21 ultra, I didn't increase the definitions, the only thing that has changed is the new anki card type I think and the fact that I updated the app.

**Comment by lrorpilla** [comment]
Hey, thanks for getting back to me. I'm going to make a way to limit duplicate checks to only a limited, customizable subset of card types in the future.

I'll try to hotfix this, in the meantime, I recommend decreasing the number of results returned by the search algorithm in the dictionary settings.

**Comment by amazingstar6** [comment]
Thanks! Decreasing the search results indeed makes the lag slower.

**Comment by lrorpilla** [comment]
Hi @amazingstar6, this is just [**a quick candidate hotfix**](https://drive.google.com/file/d/17vFkakQMuR7wA5zT8RNXrDu8P0wz_TeT/view?usp=share_link) I made up just now which tries to run the duplicate check in another thread.

Can you please see if there is any improvement?

**Comment by lrorpilla** [comment]
@amazingstar6 I see you've already reacted to 2.7.2. How is it for you?

**Comment by amazingstar6** [comment]
It works just like before (: thanks for fixing it so quickly!

**Comment by lrorpilla** [comment]
Looks like I'll just have to re-release this as it doesn't handle card types that have been deleted safely, will do that briefly.

**Comment by lrorpilla** [comment]
Re-released just now @amazingstar6
