### ISSUE TITLE
Sub not displaying properly

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#23]
I was watching 史上最強の弟子ケンイチ and noticed that some lines were cut due to the way the sub file is formatted.
Here's an example of the error: https://streamable.com/l8epm5
Here's the lines:
Dialogue: 0,0:02:07.12,0:02:09.37,a,,0,0,0,,（田中(たなか)）\N前から\N気になってたんだけど Dialogue: 0,0:02:09.58,0:02:10.38,a,,0,0,0,,（島山(しまやま)）\Nん？

Dialogue: 0,0:02:25.60,0:02:29.52,a,,0,0,0,,（田中）\Nでも 風林寺ってさ\Nどっか近寄りがたいよな Dialogue: 0,0:02:29.64,0:02:32.19,a,,0,0,0,,住んでる世界が違うっていうか…

**Comment by lrorpilla** [comment]
I will need the subtitle file itself in order to investigate this. Thanks.

**Comment by Feripe-a** [comment]
First I used .srt then I converted to .ass to see it the bug continues. Here it is https://www.mediafire.com/file/rm7dndn8vok27lo/subused.tar.gz/file
I was using .ass in that video.

**Comment by lrorpilla** [comment]
Thanks for getting back to me. I'll properly investigate this in time. Do you find this issue is critical in other subtitles you use or is this a rare occasion?

**Comment by Feripe-a** [comment]
It depends. It didn't happens in Yuru Camp because each subtitle line wasn't split in two to occupy lass space on the screen (it's different from → to indicate that the sentences continues in the next line). But the way subtitles are formatted in 史上最強の弟子ケンイチ makes that bug happens in every episode. You can download all of 史上最強の弟子ケンイチ subtitles on Kitsuneko.
I've looked into my anime folder for more subs formated that way. Bleach is formatted like that as well. So if watch it with Jidoujisho, subs are likely to "get cut".

I'm a normal user, so I can't help you that much.

**Comment by Feripe-a** [comment]
> Do you find this issue is critical in other subtitles you use or is this a rare occasion?
Yes, because only the parts that appear are copied to Anki, even though it's trimmed as it's supposed to be. I just remembered it right now.

**Comment by lrorpilla** [comment]
I have implemented a fix for this issue in [**0.24.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.24.0-beta).

See the relevant line in the release notes:
* Fixed a **critical issue** related to the **subtitle wrapper widget not parsing** and displaying files with **subtitles with more than two lines of text**

Sorry that it took a while. You actually discovered an issue in this package I'm using for subtitles. I've let the maintainer know with a pull request, so thanks for the report. If there are any further issues, let me know. With that, I am closing this issue.

**Comment by Feripe-a** [comment]
> Sorry that it took a while.
You were fast, thanks.
>If there are any further issues, let me know.
I'll be on the lookout.
