### ISSUE TITLE
Word Frequency

### ISSUE THREAD

**Issue by Lyhcan** [lrorpilla/jidoujisho#235]
Hello! does jidoujisho support frequency lists? i have a frequency list that i use on the Migaku extension and was wondering if jidoujisho supports it? it's a json file, i tried to import it on jidoujisho with no success, maybe it's not correctly formated?

The migaku frequency lists works like this: The first word in the list is "THE" therefore it's frequency is 1 (because its the first word in the list), so if i search THE in the dictionary it will show me 1, etc.. ) here is a screenshot and the file at the end: 
![Screenshot 2023-05-28 234337](https://github.com/lrorpilla/jidoujisho/assets/132207809/37f8285c-a204-4021-95f7-cc24b280182d)
[Corpus English Frequency List.zip](https://github.com/lrorpilla/jidoujisho/files/11587884/Corpus.English.Frequency.List.zip)

**Comment by lrorpilla** [comment]
Hi @Lyhcan. Unfortunately, jidoujisho only currently supports frequency dictionaries imported from the Yomichan format.

Anyone can write an implementation for frequency importing for the Migaku format, but at the time this is not planned. I intend to release developer documentation on how to extend dictionary format support for the app in the near future.
