### ISSUE TITLE
Crashes upon dictionary lookup due to ankidroid

### ISSUE THREAD

**Issue by exc4l** [lrorpilla/jidoujisho#244]
{jidoujisho}  {Error}  {}  {04062023}  {ERROR}

As stated in the title, I currently experience crashes every time the app tries to look a word up.

Events that lead to a crash:
Install Jidoujisho (tried 2.7.4 and 2.8)
Import JMdict (I tried the tmw one and the one linked on the yomichan website)
look up any word

I've attached some logs and it seems that ankidroid is the problem.
Even when removing the ankidroid permission, jidoujisho crashes on every look up, which you can also see in the logs. Why make the app so dependent on another app?

I just want to consume/read and do not care about the anki part but I also don't want to remove ankidroid from my phone just so jidoujisho doesn't crash. I'm currently updating ankidroid and have it sync with my collection. Will report back if that fixes the issue. Then it all comes down to if you want to force people to keep their ankidroid up to date.

[jidoujisho logs.txt](https://github.com/lrorpilla/jidoujisho/files/11646193/jidoujisho.logs.txt)

**Comment by exc4l** [comment]
Updating Ankidroid and giving jidoujisho permission again, did indeed fix the crashing. I would still prefer if the ankidroid part was optional.

**Comment by lrorpilla** [comment]
> Why make the app so dependent on another app?
This is a bug caused by duplicate checks. I will hotfix this as soon as possible.

**Comment by lrorpilla** [comment]
I have hotfixed this and re-released 2.8.0 with this fix just now. I have tested it to work for the case when AnkiDroid isn't installed and when AnkiDroid permissions are not granted.

Please let me know kindly if this is otherwise, as this was a timely fix.
