### ISSUE TITLE
Allow Different Values for how many seconds to seek forward and backward

### ISSUE THREAD

**Issue by Hirosashii** [lrorpilla/jidoujisho#255]
When I double-tap the left side of the screen, it seeks backwards 10 seconds, and the right side seeks forward 10 seconds. Very often, this is too many seconds, and I was wondering if it was possible to allow us as users to set how far forward or back we'd like to seek.

Additionally, would it be possible to make some simple keyboard controls? Perhaps Spacebar pauses and unpauses a video, and left and right arrow seek backwards and forwards respectively? This is much less important; just curious.

Thank you for your time!

**Comment by lrorpilla** [comment]
This is implemented in 2.8.3. Keyboard support is out of the scope of the project for now as I only support Android touch devices, hope this is of sufficient help.
