### ISSUE TITLE
Bug- Line Breaks Inserted Before Sentence

### ISSUE THREAD

**Issue by ccos89** [lrorpilla/jidoujisho#259]
Hey,

Been using for about a year/year and a half and I am running into a new bug after upgrading yesterday. When i use the “Massif Example Sentence” user enhancement in the card creator now, when it inserts the word it is adding two line breaks before it pastes in the sentence, which I have to delete. Fully open to it being me screwing something up, but I’ve never had this happen before despite having the same work flow. 

Also, thank you so much for this incredible software. It has been instrumental to my learning process and it easily outclasses paid software in the same field.

**Comment by lrorpilla** [comment]
I recommend using `SELECT` instead of `APPEND`, which doesn't have this behavior, but this should also be fixed in 2.8.5.

**Comment by lrorpilla** [comment]
I've decided to unrelease 2.8.5 as the changes are a bit rash and I'm a bit busy to re-release it.

This behaviour only ever happens if you used Append instead of Select, so I recommend using Select if you are starting with a blank field.

**Comment by lrorpilla** [comment]
@ccos89 Uploaded 2.8.5 with an appropriate fix.

**Comment by ccos89** [comment]
Thank you! Working great now with the update, cheers.
