### ISSUE TITLE
JMdict V2 not being imported in version  0.24.5-beta

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#26]
I tried to import JMdict V2 ([available for download here](https://anacreondjt.gitlab.io/docs/dicts/)) using 0.24.4-beta and 0.24.5-beta but it wasn't imported, [as you can see in this video](https://streamable.com/jmu864). That's strange. It had been imported in version 0.24.2-bata. Other dictionaries are being imported but JMdict V2 isn't anymore.

**Comment by lrorpilla** [comment]
Another user has reported a version of the JMdict that previously worked won't import now, I'll investigate this some other time but for now I recommend [this pretty well updated JMdict from the Yomichan site](https://foosoft.net/projects/yomichan/) that imports just fine.

**Comment by lrorpilla** [comment]
This is resolved in the hotfix for [**0.25.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.25.0-beta). You may need to clear application data for it to work.

See the relevant release notes:
* **(Hotfix)** Fixed an issue where **dictionaries with double values for popularity** such as [**JMdict V2**](https://anacreondjt.gitlab.io/docs/dicts/) could not be imported as **an integer was used**.

The dictionary imports well so I am closing this issue. If there are any further issues, feel free to re-open and let me know.

**Comment by Feripe-a** [comment]
Thanks. Fast as always!
