### ISSUE TITLE
Multi Frequency export

### ISSUE THREAD

**Issue by HoanPiTa** [lrorpilla/jidoujisho#265]
Hi. Now we just can export 1 frequency dict. Please support more than.
Thank you

**Comment by lrorpilla** [comment]
Hi @HoanPiTa, this app is in maintenance mode so I don't take feature requests at the moment. There's another developer I speak to that has expressed a desire to implement field-specific settings, but I am busy at the moment.

Again, since I am on hiatus, I do not plan to implement new features.
