### ISSUE TITLE
Manga Grey Screen v 2.8.5

### ISSUE THREAD

**Issue by blakedgross** [lrorpilla/jidoujisho#266]
When I open mokuro processed manga it doesn't render anything and is just a grey screen. Attached is my logcat capture. 

[debug.txt](https://github.com/lrorpilla/jidoujisho/files/11923957/debug.txt)

**Comment by lrorpilla** [comment]
I need a screenshot and a better description of this issue to action this.

Likely, this is a filename issue.

**Comment by blakedgross** [comment]
Thank you for your help, I was not using it correctly.
