### ISSUE TITLE
Couple of feature idea.

### ISSUE THREAD

**Issue by T1CkShot** [lrorpilla/jidoujisho#27]
I think the following features will help advanced learners.

> Show subtitle on pause.
Keeps the subtitle hidden and only shows it when the video is paused.

> Show subtitle on repeat.
Keeps the subtitle hidden and shows it when the part of the video is repeated.

Thanks a lot for such a great app 😀.

**Comment by lrorpilla** [comment]
Hi, T1CkShot, thanks for your feedback.

I believe what you're describing is mostly already fulfilled by **Listening Comprehension Mode** which you can find in the player menu. I recommend trying that out, it only shows the subs when you flick back to it or use the transcript. For the show subtitles on pause, I recommend just opening the transcript every now and again when also using Listening Comprehension Mode.

If this doesn't aptly fulfill what you want, feel free to re-open this issue.

**Comment by lrorpilla** [comment]
Listening Comprehension Mode didn't quite fulfill the *Show subtitle on pause* part of your requests, so I've gone ahead and fulfilled that in [**0.25.3**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.25.3-beta).

See the following line in the release notes:
* Subtitles will now show when pausing in `Listening Comprehension Mode`

I believe the mode will satisfy both of your requirements now.

**Comment by T1CkShot** [comment]
Thanks a lot. Really appreciate the work you are putting in to help the
language learning community.

**Comment by lrorpilla** [comment]
I appreciate it. Looks like I will need to release a hotfix for this as there seems to be a shadowing mode related problem when you load a video which loops it.
