### ISSUE TITLE
[improvement] Implement subtitle font face, color, and potentially size configuration options

### ISSUE THREAD

**Issue by ShiroiKuma0** [lrorpilla/jidoujisho#270]
Improvement idea: could you add a configuration option for the subtitle font face, color, and size. It would be beneficial to be able to modify the subtitle look. The size could be modifiable by a gesture while the video is playing.

Also, the display font size for the dictionary could be modifiable - but this might be a more intense programming task. Anyhow currently, the only way to increase or decrease the size is via system settings - but then that affects every other app on the phone.

**Comment by lrorpilla** [comment]
Hi, please note this app is in maintenance mode. You can modify subtitle font and size in the in-player subtitle settings.

I am currently in hiatus and will not be taking feature requests at this time.
