### ISSUE TITLE
[error] Import in progress, IsarError: The database is full

### ISSUE THREAD

**Issue by ShiroiKuma0** [lrorpilla/jidoujisho#271]
On importing some dictionaries - not all - I get (in the "Import in progress" pop-up box) the following error message:

IsarError: The database is full

It fails to import the database then.

**Comment by lrorpilla** [comment]
I recommend using slow import, otherwise this issue may appear varied on what device you're using really.

**Comment by ShiroiKuma0** [comment]
This is during slow import - Samsung Fold 4.

**Comment by lrorpilla** [comment]
Will just have to try your luck or maybe do a hard reset. Can't be of much help with this issue, unfortunately.
