### ISSUE TITLE
JPDB integration

### ISSUE THREAD

**Issue by Helmasko** [lrorpilla/jidoujisho#277]
It would be great if this app could support JPDB integration in a similar way this does https://github.com/max-kamps/jpd-breader
where known and unknown words get coloured and furigana can automatically be added.

to get access to the public API you might need to ask the owner in their discord server https://discord.gg/zcEFYTXVdN

**Comment by lrorpilla** [comment]
Unfortunately, this is something that I am not interested to implement myself. I don't think I like the idea of this feature very much, though I won't stop a pull request from being made if anybody else is adamant about it.

I know your question is a bit different but please see the [relevant FAQ item here](https://github.com/lrorpilla/jidoujisho/wiki/1.-FAQ#will-you-support-highlighting-known-words-in-text).
