### ISSUE TITLE
Dictionary term search should be smarter

### ISSUE THREAD

**Issue by ttu-ttu** [lrorpilla/jidoujisho#28]
Currently if one searches for `原色擬似概念` on a *local* dictionary, it report that it has no results, even tho `原色` exists in the dictionary.

My suggestion is to make the search more lenient so that it supports words shorter than the highlighted ones.

**Comment by lrorpilla** [comment]
I've made fallback terms more lenient in [**0.25.2**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.25.2-beta) as an experiment so I'll have to see over the next days how this is received. 

I had existing logic for this but I seem to have neglected this edge case. The change makes use of the text segmentation result as a fallback if no exact results are found.

I'll probably revisit this if there are any
