### ISSUE TITLE
Volume button page turning doesn't work until you tap the page

### ISSUE THREAD

**Issue by darren-moore** [lrorpilla/jidoujisho#280]
1. Ensure Volume button page turning is enabled for ttu.
2. Open book in ttu.
3. Press volume buttons before tapping the page. Note the volume is adjusted rather than the page turning.
4. Tap the page to "hook" the buttons in
5. Now the volume buttons turn the page as expected.

- It seems that swiping doesn't count for "hooking" the buttons in- you must tap the page.
- This can also be reproduced by locking a device with ttu open, then unlocking. Once again you must "hook" the buttons in with a tap.
- I believe this is the same with the mokuro reader.

I am on version 2.8.7, and this happens across multiple devices.

**Comment by lrorpilla** [comment]
This is unfortunately expected behavior, and is a platform limitation.
