### ISSUE TITLE
Shortcut for switching sub languages

### ISSUE THREAD

**Issue by NielsVandenEynde** [lrorpilla/jidoujisho#286]
It would be nice to have the ability to easily switch between english and japanese subs. Sometimes you really need to look at the translation to understand a sentence.

**Comment by lrorpilla** [comment]
This is working as intended -- It is an active effort to perform and is the implicit cost of having to look at native subtitles. Please refer to the [**relevant FAQ section**](https://github.com/lrorpilla/jidoujisho/wiki/1.-FAQ#will-you-support-having-multiple-subtitles-at-once).
