### ISSUE TITLE
How to keep furigana ? 

### ISSUE THREAD

**Issue by boqxfjge** [lrorpilla/jidoujisho#287]
Is there a way to keep the furigana data identified by the Ruby tag  when converting the MDX dictionary to  formats supported by this app?

**Comment by lrorpilla** [comment]
At present, no. Since I'm not really understanding your motivation, it would help if you would share with screenshots or some context, otherwise I can't really be of help.

**Comment by boqxfjge** [comment]
I am a Chinese. Japanese kanji are similar with Chinese, but the pronunciation is quite different. When I read Japanese, I always subconsciously pronounce the kanji as Chinese pronunciation in my mind. And because I am so familiar with the meaning of the kanji that I often unconsciously ignore the fact that I am not sure how to pronounce them. So, I always prefer to choose dictionaries with phonetic notation to remind me of the right pronunciation. 
I wanna know if there is a way for users to retain phonetic notation when converting dictionary formats to import into this app.
![IMG_20230731_175246](https://github.com/lrorpilla/jidoujisho/assets/113582398/8faee323-c37f-428d-9056-9284ca03e0de)

**Comment by lrorpilla** [comment]
Unfortunately, the app for now doesn't support structured content, which would be needed to support Ruby or anything other than plain text from Yomichan dictionaries. The relevant issue is tracked here -- #174. There is experimental progress towards fixing this issue but it's unlikely to progress while I'm on hiatus in the meantime.

I do understand what you want to do now and what you're struggling with. The best thing right now is to double tap to smart select words to recursively search, or tap on kanji in the headwords of dictionary entries to learn their reading if you import a Yomichan dictionary with kanji banks like KANJIDIC.

That is the case for now, I'm afraid to say.
