### ISSUE TITLE
Ttu reader personalized data sources 

### ISSUE THREAD

**Issue by aoimonster** [lrorpilla/jidoujisho#294]
Ok, so I set in ttu reader an specific data source that I create from Google drive but I can't acces it because it doesn't let me register to my Google account to give permission, could you add this to future updates? Or there are security problems about it?
![Screenshot_2023-08-21-21-45-11-909_app lrorpilla yuuna](https://github.com/lrorpilla/jidoujisho/assets/130512347/376f4096-8e05-43f9-a9a0-7515360f787c)

This is what it appears me when I try to login ↑

**Comment by lrorpilla** [comment]
Please refer to [this section in the wiki](https://github.com/lrorpilla/jidoujisho/wiki/2.-Troubleshooting#i-have-trouble-setting-up-cloud-sync-with-%E3%83%83%E3%83%84-ebook-reader).

**Comment by aoimonster** [comment]
> Please refer to [this section in the wiki](https://github.com/lrorpilla/jidoujisho/wiki/2.-Troubleshooting#i-have-trouble-setting-up-cloud-sync-with-%E3%83%83%E3%83%84-ebook-reader). If this doesn't solve your problem, feel free to re-open but I believe it relates to this.

Is just it can't understand what is exactly what I have to change; the section of the wiki says that my link has to be changed from just auth to auth.html, wich i think is already changed by default:
![Screenshot_2023-08-21-23-32-12-206_app lrorpilla yuuna](https://github.com/lrorpilla/jidoujisho/assets/130512347/07dc52f7-ba76-4222-b26d-0bb24ef1f64e)
Please if you just can tell me how I can change the link, port etc I would, because in the whole app I can't see anything to do that, maybe I'm blind. 
Thanks a lot for answering

**Comment by aoimonster** [comment]
Lol, bad 

> Please refer to [this section in the wiki](https://github.com/lrorpilla/jidoujisho/wiki/2.-Troubleshooting#i-have-trouble-setting-up-cloud-sync-with-%E3%83%83%E3%83%84-ebook-reader). If this doesn't solve your problem, feel free to re-open but I believe it relates to this.

Is just I don't know what I have to change exactly or where to do it.
Where can I change the link to be from auth to auth.html? Or the port etc. Sorry if I'm stupid or blind but I just simply don't know where I have to change that, I don't see it neither inside ttu reader or is a setting in the app.
Thanks a lot for answering!

**Comment by lrorpilla** [comment]
This is a setting pertaining to your GCP setup for your own TTU storage source.

See: https://github.com/ttu-ttu/ebook-reader#storage-sources
