### ISSUE TITLE
Is it possible to de-inflect conjugated words with yomichan dictionaries ?

### ISSUE THREAD

**Issue by kaine-nier** [lrorpilla/jidoujisho#299]
Hello, firstly thank you for this amazing app, I especially love the mokuro feature.
Though I don't know if there is something I'm doing wrong or if it isn't supported but is it possible to de-inflect words like in yomichan ?
For example having a conjugated word like 止められた and having "potential or passive, past" next to the 止める entry in dictionary ?
I only use yomichan dictionaries ( the ones from the Foosoft page like JMdict) . I don't know if it's a problem because of structured content as described here #174 so i'm sorry for creating this issue if this is the case.
Thanks.

**Comment by lrorpilla** [comment]
Unfortunately, this is something I explicitly do not plan to support.
