### ISSUE TITLE
Doesn't load external .srt by default and can't locate any to load manually 0.3.2/0.4.2(non android 11 version) 

### ISSUE THREAD

**Issue by Suakwe** [lrorpilla/jidoujisho#3]
Samsung Galaxy S7 running Android 8

When selecting a video through Play Local Media you can see both the video and .srt files, but when clicking Load External Subtitles no files can be located, there's no dropdown arrow to change location away from recent, and the "open from" menu doesn't show the phone's local storage.

<details>
  <summary>Play Local Media</summary>
  
![ss1](https://user-images.githubusercontent.com/78872974/107561354-5a0c8f00-6c2e-11eb-9bd5-81effe03b174.jpg)
![ss2](https://user-images.githubusercontent.com/78872974/107561366-5d077f80-6c2e-11eb-839b-1770dc533398.jpg)
</details>
<details>
  <summary>Load External Subtitles</summary>
  
![ss3](https://user-images.githubusercontent.com/78872974/107561428-6e508c00-6c2e-11eb-8256-545cce0bcb0e.jpg)
![ss4](https://user-images.githubusercontent.com/78872974/107561431-6f81b900-6c2e-11eb-9830-4f0e6619b495.jpg)
</details>

0.3.1 loads .srt files by default but doesn't have the Load External Subtitles option so couldn't test that.

**Comment by lrorpilla** [comment]
Greetings, external .SRT files no longer loading by default is an artifact of changes I needed to make in order to get the app running on Android 11. It is impossible for the external .SRT files to be known to the app without picking a separate file with the file picker once more after you select the video file.

Truth be told, I myself use the app on 0.3.1 on my own Android 10 device because I'm not satisfied with how files have to be accessed in newer versions of the app, and plan to separate the way files are handled below and on/above Android 11 (to use the older and newer system respectively).

The way .SRT files aren't showing in your menu are a separate issue, however. I will look into it as soon as I can.

**Comment by Suakwe** [comment]
Ahh no worries, wasn't sure if that was the case or if only the Android 11 version wasn't able to load by default so figured I'd mention it.

Tried troubleshooting by moving some video and .srt files to an SD card to see if that could change anything but still couldn't locate any files. Did find a new issue however, one .mkv file I tried would play audio and show embeded subtitles, but the video was just black with horizontal line artifacting; the video also had this issue when testing it on mpv for Android, but I was able to fix it on that by turning off Hardware Decoding. I can open a new issue if you think its worth looking into.

**Comment by lrorpilla** [comment]
I can't test beyond what videos and devices I have, so thank you for the initiative. Other users seem to be having trouble with Matroska videos, some not playing at all and now what you've just discovered.

I'm motivated to switch from ExoPlayer which I am currently using right now to VLCKit which should allow videos to behave and be decided exactly like they are on VLC -- it's working but there's just one issue that prevents me from releasing the release just yet (auto-rotate is not very smooth with it).

Thanks again for the heads up.

**Comment by lrorpilla** [comment]
I have fixed the issue with .SRT files not showing via the "Load External Subtitles" option and in addition added support for .ASS files in 0.4.3.

Unfortunately, I'm unable to migrate the app to VLCKit as it's not working as elegantly as I want it to. I'll update when I have details but for now, I'm closing this as the relevant issue is fixed.

**Comment by lrorpilla** [comment]
I am briefly reopening this issue to announce that [I have recently migrated the app to use VLCKit in the 0.6.0 release](https://github.com/lrorpilla/jidoujisho/releases/tag/0.6.0-beta) and that the videos you are having issues with should now be compatible.

If there are any further issues, please let me know. And with that, I am closing this issue.
