### ISSUE TITLE
[Feature Request] A way of dealing with furigana in subtitles.

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#30]
I've found a problem with subs that have furigana, mainly those you find on Netflix subs.
![Screenshot_2021-07-11-20-15-59-816_com lrorpilla jidoujisho](https://user-images.githubusercontent.com/84395172/125212710-b16a6600-e285-11eb-9795-5fbbf6dd56e5.jpg)
![Screenshot_2021-07-11-20-16-37-395_com lrorpilla jidoujisho](https://user-images.githubusercontent.com/84395172/125212713-b29b9300-e285-11eb-95e3-bf24002dcc8b.jpg)
![Screenshot_2021-07-11-20-22-36-690_com lrorpilla jidoujisho](https://user-images.githubusercontent.com/84395172/125212726-cb0bad80-e285-11eb-8b8a-d83c500b3f7a.jpg)
![Screenshot_2021-07-11-20-22-44-318_com lrorpilla jidoujisho](https://user-images.githubusercontent.com/84395172/125212730-cc3cda80-e285-11eb-8fc3-de99ef6deb57.jpg)
The word can't be parsed at all because there's furigana on almost every kanji. My request is:
* Skip furigana when parsing;
* Option to turn furigana on and off (because it might be helpful for some users);
* Automatically remove furigana when a cards is created.

You can find the subtitle in the screenshots [here](https://mega.nz/#!jS5ykQbI!8OZ5PDKaNaMWLY4Yr1xbs4lRiexsRJjAmJ1CgnKTh7c). But it's pretty common to have furigana in subs — I personally find them annoying.
I'm not aware of other patterns to indicate furigana, so far I've only encountered the one present in the screenshots. There might be more patterns.

**Comment by lrorpilla** [comment]
Seems to be exactly related to [this Yomichan issue](https://github.com/FooSoft/yomichan/issues/1195) and I will have to offer a similar solution.

**Comment by lrorpilla** [comment]
I am on hiatus but this is pretty easy to offer a band-aid solution to this with a regular expression filter so I've gone ahead and implemented it in [0.25.5](https://github.com/lrorpilla/jidoujisho/releases/tag/0.25.5-beta).

You will need to apply the following filter if you want to hide anything within parentheses as per the linked Yomichan solution: `[(]([^)]*)[)]`and be sure to **set and remember** if you want to keep the filter across all following videos.

I believe this is a broad solution that can be adaptable to different ways Furigana can be represented and you will have to be proficient in regular expressions should you find a format that doesn't quite fit the Netflix subtitles pattern but the filter above should function well enough for your purposes.

I should mention I will be on hiatus for a short while, so if there are any newer issues I won't be able to address them as soon as I have, I should be reading but I figure this one change is pretty fast enough to make. 

If there are any additional issues, feel free to re-open.

**Comment by lrorpilla** [comment]
I've reuploaded that release so that the filter should also work on subtitles upon export.

**Comment by Feripe-a** [comment]
>I should mention I will be on hiatus for a short while

No problem. Go and immerse yourself. I've doing a great job lately. We really appreciate the time you've spent developing this tool.
