### ISSUE TITLE
Cannot import epub into ttsu reader

### ISSUE THREAD

**Issue by xthemeraldkingx** [lrorpilla/jidoujisho#304]
Bookimport failed
Error importing [book name].epub: k.replaceAll is not a function

this happens with multiple books so it must be a device problem

**Comment by lrorpilla** [comment]
Do you have the latest Android WebView?

**Comment by xthemeraldkingx** [comment]
Yes it wasn’t installed before but its still not working even after installing it

**Comment by lrorpilla** [comment]
I will need some more information about your device, and what Android version you're on

**Comment by xthemeraldkingx** [comment]
It’s an android e-reader, Meebook P78 Pro
Android 11, kernel version 4.19.193-ab377
I can’t really find anything else, but only the armeabi apk worked, the arm apk wouldn’t install.

**Comment by Bluemoondragon07** [comment]
Same here! Using a Meebook M7, which is also Android 11 and has the same specs. I also installed Android WebView and it returns the same error. I have tested it with several e-books.

**Comment by Bluemoondragon07** [comment]
Are there other essential components that Jidoujisho require other than Android Webview?

**Comment by lrorpilla** [comment]
A significant number of users who report issues are on a 32-bit Android device, I'm not sure what the case is for `armeabi` users but that's just a hunch observation

**Comment by Bluemoondragon07** [comment]
@xthemeraldkingx I found a fix! Install Android Webview under Tools in App Store (Meebook's Appstore, not Google Play). I don't know why, but that specific version of webview they provide for Meebook devices is the only one that works correctly with Jidouisho.

**Comment by xthemeraldkingx** [comment]
Thanks so much!! It works now :D

**Comment by Joe-K2018** [comment]
> @xthemeraldkingx I found a fix! Install Android Webview under Tools in App Store (Meebook's Appstore, not Google Play). I don't know why, but that specific version of webview they provide for Meebook devices is the only one that works correctly with Jidouisho.

Thank you! Thank you! New Meebook M7 owner here and that fixed it for me too. I bought this thing specifically for Jidoujisho so I'm very happy to get it working!
