### ISSUE TITLE
OCR for physical media

### ISSUE THREAD

**Issue by UngluedBike** [lrorpilla/jidoujisho#310]
Unsure how practical/achievable this would be, but it would be really cool to be able to scan text in a similar way to Google lens and make a card on the fly (maybe there is a way to integrate lens into the app idk). Would be fantastic to use this for physical media too!

**Comment by lrorpilla** [comment]
Hi, please refer to this section in the [FAQ](https://github.com/lrorpilla/jidoujisho/wiki/1.-FAQ#will-you-support-optical-character-recognition).
