### ISSUE TITLE
Jidoujisho 2.9.0 not displaying frequency dictionaries at all

### ISSUE THREAD

**Issue by phamthaison1207** [lrorpilla/jidoujisho#311]
This is quite simple, version 2.9.0 doesn't seem to be showing frequency dictionaries
![test](https://github.com/lrorpilla/jidoujisho/assets/63585568/e2707da7-bcd0-4ce6-8205-564cda94c80a)
![test2](https://github.com/lrorpilla/jidoujisho/assets/63585568/b6d02f20-ca76-4602-b26f-ab43e3c092ff)
![test3](https://github.com/lrorpilla/jidoujisho/assets/63585568/c4ef6501-e412-45a6-b876-5a956a26fd6e)

**Comment by lrorpilla** [comment]
I have frequency dictionaries showing fine. Is this from a fresh installation?

**Comment by lrorpilla** [comment]
I have imported several frequency dictionaries and they display fine, so I'm not sure what is up here.
![Screenshot_20231009-191605](https://github.com/lrorpilla/jidoujisho/assets/11363922/62e58c9b-c002-434b-87be-8aae585a3c5f)

**Comment by phamthaison1207** [comment]
thank you for noticing my isssue, I have decided that this problem is closed because  it is not your bug, it was a user-side problem, I installed 2.9.0 with the wrong manner of installation and it resulted in these bugs that I encountered, if you wanna know specifically, I am happy to provide more, but this is it here, thank you for noticing my problem too.
