### ISSUE TITLE
Skip silent scenes when subtitles are on

### ISSUE THREAD

**Issue by FahadHeiji** [lrorpilla/jidoujisho#314]
#### Credit:

I would like to thank you again for your wonderful application. It has made many things easier for me and made my productivity 5 times more so thank you for making this application.

#### The problem:
The problem is that when subtitles are turned on, scenes that do not contain text are skipped. At first I thought the problem was with the subtitle file, but I did not find any problem with the timing. I checked the episode without subtitles I found that it did not skipped.

Here's a video showing the problem:

https://github.com/lrorpilla/jidoujisho/assets/114103612/faabedb3-1314-4705-96de-83a487e5e544

**Comment by lrorpilla** [comment]
Can you show a video with you changing the current playback mode?

**Comment by FahadHeiji** [comment]
Indeed, this is the reason I apologize for not noticing this feature.

https://github.com/lrorpilla/jidoujisho/assets/114103612/38666ef7-6613-4ede-86d5-d49dccdc327a


![Screenshot_2023-10-22-13-25-14-71_d1e85489dfcf960faafc2f4d5db41573](https://github.com/lrorpilla/jidoujisho/assets/114103612/08ccf069-7e62-44b3-934c-511dd4e18658)
