### ISSUE TITLE
Can't view any YouTube videos, but comments and subtitles are able to load

### ISSUE THREAD

**Issue by RoseTanuki** [lrorpilla/jidoujisho#319]
Here is a screen recording that I hope shows the issue
https://youtu.be/pFh-EPyqBek?si=VHoKEGsH7c0YMa-j
![Screenshot_20231025-130632](https://github.com/lrorpilla/jidoujisho/assets/123436298/2d79d762-d9f1-4995-a1a8-7e932d4b28ad)
![Screenshot_20231025-130638](https://github.com/lrorpilla/jidoujisho/assets/123436298/92bfed50-0518-46cf-973b-b4f632b8150b)

**Comment by lrorpilla** [comment]
I'm on a Pixel 7 Pro and can't reproduce this. I'll note this down but I've tried to play videos of the same channel and they appear to work fine.

**Comment by lrorpilla** [comment]
Does changing the video quality change anything?

**Comment by RoseTanuki** [comment]
This issue is fixed for me now. I uninstalled jidoujishou and updated to the latest version. I also updated Android WebView.
