### ISSUE TITLE
[Feature Request] An easy way to favorite sentences on the fly

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#33]
It would be awesome if we could mark/favorite/save dialogues to look up words after we've finished watching.

**Comment by Feripe-a** [comment]
It could be something like a small star button somewhere on the screen.

**Comment by lrorpilla** [comment]
Hi, @Feripe-a, for this same use case I made the Context feature. You can revisit any words in the exact subtitle or scroll position you found them in from any book or video you feel like adding by long-pressing on a dictionary entry and returning with the Context feature. By revisiting those contexts, you will be able to mine the context where you previously weren't ready to.

The Dictionary tab holds the last 50 lookups you've done. Let me know if this is insufficient or doesn't fit with your use case.

**Comment by Feripe-a** [comment]
Lol
There was this feature all the time?

**Comment by Feripe-a** [comment]
>⌛ Users may select Context from a dictionary result to go back to the exact duration in video or scroll position in book

....... Sorry for wasting your time.

**Comment by lrorpilla** [comment]
That's quite alright, lol
Have fun immersing ^^

**Comment by Feripe-a** [comment]
Likewise
