### ISSUE TITLE
instant export shortcut button doesn't work

### ISSUE THREAD

**Issue by RoseTanuki** [lrorpilla/jidoujisho#337]
I just installed the latest version of jidoujishou, and I can't use the instant export button. But I can create a flashcard with the card creator button.

I installed this version:
jidoujisho_yuuna_2.9.0_preview-arm64.apk

Model: Pixel 2 XL
Android 11

Here's a video of my problem
https://youtu.be/kkcq1j63RJI?si=geSsChxDOzcHNrOe

**Comment by RoseTanuki** [comment]
I think I found my problem! I only have this issue with the new jitendex yomitan dictionary entries. Monolingual dictionaries work fine. So I'll probably have to dig up a legacy version of jmdict to use instead, since that worked in the past for me.

**Comment by sorata225** [comment]
Go to MarvNC's github repo and You'll find the latest version for use. You don't need a legacy version. Download the other from there.
