### ISSUE TITLE
keeping older anki compatibility

### ISSUE THREAD

**Issue by JunkyardCat** [lrorpilla/jidoujisho#342]
can you retain the compatibility of older ankidroid? sometimes other plugins and stuff work better on the older anki and i havent really update my ankidroid yet

is this possible

**Comment by JunkyardCat** [comment]
@lrorpilla hi i know you closed this but just to ask if its possible to retain the old method of sending to anki. like you will still develop on newer anki but at least keep the old anki connection around. so kind of like export to anki, export to anki old upto x.x, export to anki old x.x. or maybe a toggle in the settings

**Comment by lrorpilla** [comment]
This is tied to the dependencies used by the app which are included and specified upon building for Android.

Unfortunately, it's one or the other and it's in the perspective of an API consumer of AnkiDroid, out of my control and would require building and releasing and maintaining two separate versions of the app.

This will result to six permutations, for three device architectures and two possible API versions, so unfortunately it's just infeasible from a developer perspective.

**Comment by xrishox** [comment]
> sometimes other plugins and stuff work better on the older anki and i havent really update my ankidroid yet

what things do you use that prevent you from being able to use the most recent ankidroid?

**Comment by JunkyardCat** [comment]
@

> > sometimes other plugins and stuff work better on the older anki and i havent really update my ankidroid yet
> 
> what things do you use that prevent you from being able to use the most recent ankidroid?

i guess its just me having anxiety that it may fail. like im ok now with my anki but maybe if i install a newer version itll break something

**Comment by xrishox** [comment]
if your setup already works for you and you dont want to mess with it then you can just not update either of them.

**Comment by JunkyardCat** [comment]
@xrishox 
i understand where your coming from but there are also time where i want a specific feature that can only be found on the newer version. :)
