### ISSUE TITLE
Ability to use my own anki card templates (enhancement)

### ISSUE THREAD

**Issue by ONEsuzuki** [lrorpilla/jidoujisho#346]
I have lots of cards with a template I really prefer to the default, surely it's possible to choose from my own note types since I can see my decks from jidoujisho, if I could just re-assign the necessary fields from the jidoujisho template to my own note type, allowing the default for people who use it. 

I see a way of customizing the quick buttons in the app, but I find it rather complex to navigate, just checking there isn't already a way of doing this?

Off topic: 
Great app, just wish it had Netflix integration the reader is flawless though, even the WEB, screw kiwi browser + yomitan extension, thank you very much.

**Comment by xrishox** [comment]
you can do that by setting up your own export profile.

**Comment by ONEsuzuki** [comment]
I will have another look today, are just create a new export profile and try that. Thanks.

**Comment by ONEsuzuki** [comment]
@xrishox 
I had a look and I can see what you're saying you can do it but you can't. I wanted to do was this:
Sentence -> Sent kanji
Term -> Vocab kanji
Remapping default card fields to the fields I have it set to on my card template, just like changing key binds re-routing, it just seems so restrictive. And the boxes aren't that simple why is there a ton of closes for sentence furigana rather than just "sentence furigana"? Unless this close is for something else? 
![image](https://github.com/lrorpilla/jidoujisho/assets/111155695/694a6c8a-6f08-4b11-86fd-bc7672e8579f)

Thanks for the help.

**Comment by ONEsuzuki** [comment]
I just made a new export profile and I can see that the option was there the whole time, sorry for wasting yours.
