### ISSUE TITLE
There wan an error in adding note to ankidroid

### ISSUE THREAD

**Issue by 23894jfdk** [lrorpilla/jidoujisho#351]
Tested with ankidroid 2.17 alphas 14, 15, 17; jidoujisho 2.9.0.

Can't export to anki no matter what, tried deleting the anki folder, reinstalling, clearing caches, etc. It worked with alpha 14 once, but after deleting one of the created cards on anki, it wouldn't work anymore

**Comment by 23894jfdk** [comment]
Solved. Apparently, you can't leave the Default deck created by jidoujisho with 0 cards. In this case, the app can't add new cards to it. As soon as I created a dummy card in the Default deck, jidoujisho was able to export cards again.

**Comment by LostArrows27** [comment]
@23894jfdk i don't see the default deck created by jidoujisho in my ankidroid, can you provide more specific instruction cause i have same error....

**Comment by brishtibheja** [comment]
@LostArrows27 It doesn't create a deck for you. You select your own deck. It only creates a note type.

**Comment by 23894jfdk** [comment]
> @LostArrows27 It doesn't create a deck for you. You select your own deck. It only creates a note type.

That's right, I can't believe I had not seen the deck selector in the card creation window.



> @23894jfdk i don't see the default deck created by jidoujisho in my ankidroid, can you provide more specific instruction cause i have same error....

Try selecting other deck in the card creation window. If that doesn't work, the error must have another cause.

**Comment by LostArrows27** [comment]
@brishtibheja @23894jfdk thanks guys so much, i saw the deck selector now. It's in the bottom left of the screen so i haven't noticed that yet XD
