### ISSUE TITLE
Issues with using newlines

### ISSUE THREAD

**Issue by brishtibheja** [lrorpilla/jidoujisho#356]
I am on Redmi 12 (5g ver.) The issue I am facing requires you to turn off the feature that uses `<br>`

What happens on my phone is the card gets exported perfectly fine but newlines do not appear. I can fix this by opening note editor and re-saving the note. It is quite possible that the issue is with the API? I do not know. I tried using another third party app (takoboto) and it worked fine. 

I will be grateful if you look into this when you have time.

**Comment by lrorpilla** [comment]
I would look into the CSS template, the `pre-line` attribute here may be related.

**Comment by brishtibheja** [comment]
~~Can you explain it for a non-techie? If I'm not misunderstanding you, this would work~~

If you were talking about `<pre>` then I tried it just now. It basically looks something like this now:

![Screenshot_2024-04-29-15-15-10-65_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/lrorpilla/jidoujisho/assets/136738526/feea9312-653c-4ca9-9158-ecbeadc7ebb0)

This is how Back part of the template looks like:

`<pre>{{#Meaning}}<p><small>{{Meaning}}</small></p>{{/Meaning}}
{{#Expanded Meaning}}<p><small>{{Expanded Meaning}}</small></p>{{/Expanded Meaning}}{{#Collapsed Meaning}}<details><summary></summary><p><small>{{Collapsed Meaning}}</small></p></details><br>
{{/Collapsed Meaning}}</pre>`
