### ISSUE TITLE
Unable to Open Local Media

### ISSUE THREAD

**Issue by FahadHeiji** [lrorpilla/jidoujisho#358]
**Description:**
I am experiencing difficulty opening local media files using the application. When attempting to access media files stored locally on my device, the application doesn't respond to open the local files & showing any error message. This issue is impacting my ability to view or play local media content. 

**Screenrecord:**
https://github.com/lrorpilla/jidoujisho/assets/114103612/59c2e5e3-1203-4d6e-aa90-22a2b82d2091

**Steps to Reproduce:**
1. Open the application.
2. Navigate to the media section.
3. Attempt to open a local media file.

**Expected Behavior:**
The application should successfully open the local folders.

**Actual Behavior:**
The application fails to open the local folders, not responding.

**Environment:**
- Application Version: 2.8.9 , 2.9.0 too
- Operating System: Android 12
- Device: Realme 7 pro

![Screenshot_2024-02-20-17-27-14-46_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/lrorpilla/jidoujisho/assets/114103612/305e3b4b-a63e-4d62-8cb4-2860ddbd4e28)

**Additional Information:**
Please let me know if there are any troubleshooting steps or workarounds that can be suggested. This issue is hindering my ability to use the application effectively.

**Comment by askerrit** [comment]
why did you close this? did you find a fix?
