### ISSUE TITLE
Feature request: Showing local file name in the player 

### ISSUE THREAD

**Issue by DanTan3Machi** [lrorpilla/jidoujisho#36]
Great app that's close to perfection. I mainly use the app for playing local videos and since file names are sometimes too long I can't see the  full title of the episode from the file picker. This results in me opening an episode to realize it's the wrong one. 
It would be great if I could see the file name inside the player or maybe change the view to list in the file picker (don't no if you can control it).

**Comment by lrorpilla** [comment]
Hi, consider putting the file picker in landscape orientation by turning on auto-rotation when you pick videos, it should be a smoother experience picking videos and subtitles when you operate the app in that manner, without having to switch between portrait and landscape orientations.

You'll also gain more space for the text so you can read the number.

**Comment by DanTan3Machi** [comment]
Thanks man, that did the trick.
