### ISSUE TITLE
Can't get anki export to work 

### ISSUE THREAD

**Issue by SafriXV** [lrorpilla/jidoujisho#379]
I've been trying for a little while to get jidoujisho to connect with anki but I get "There was an error in adding a note to AnkiDroid" everytime.

The issue could be from my normal yomitan settings I found at the [Lazy Yomitan Setup Guide](https://xelieu.github.io/jp-lazy-guide/setupYomitanOnPC/) otherwise I don't really have any idea on what could be wrong.

All relevant apps were freshly installed yesterday.

![Screenshot_20240425_194800918_jidoujisho](https://github.com/lrorpilla/jidoujisho/assets/154066249/ee0b6424-9d23-4958-a370-4cb5cd82f332)
![Screenshot_20240425_195608469_jidoujisho](https://github.com/lrorpilla/jidoujisho/assets/154066249/9a7f8eff-e96f-45a5-ae7b-895c56b222b3)

Device:
Phone: Hisense A9
OS: Ink OS
Android: Version 11

Apps:
Ankiconnect - 1.13
AnkiDroid - 2.17.6
Jidoujisho - 2.8.9

All apps have every permission

**Comment by brishtibheja** [comment]
Some people are having problems with V3 scheduler. We gotta wait for now. (You can actually downgrade Anki if you want and check if that's still not working)

**Comment by SamuelHansard** [comment]
i had the same issue, it looks like you dont have a deck selected, below the image theres a dropdown menu, theres no placeholder text which makes it easy to miss but you can see the little dropdown arrow. For me that solved it.

**Comment by brishtibheja** [comment]
Oh yeah this person doesn't even have a deck selected. But I don't expect everyone was having this issue for the same reason.

**Comment by SafriXV** [comment]
> i had the same issue, it looks like you dont have a deck selected, below the image theres a dropdown menu, theres no placeholder text which makes it easy to miss but you can see the little dropdown arrow. For me that solved it.

I see.... 
thank you for your help everything works now...

**Comment by Austin-Scott** [comment]
I was having the same problem and selecting the deck fixed it. I didn't even notice that there was a select deck field, perhaps adding a "Select deck..." placeholder to that drop down field would make it more noticeable?

**Comment by Austin-Scott** [comment]
And/or perhaps if changing the error message toast to "Please select a deck" instead of "There was an error adding a note to AnkiDroid" so the user knows that it's not actually a bug
