### ISSUE TITLE
Cannot export to AnkiDroid

### ISSUE THREAD

**Issue by proy9714** [lrorpilla/jidoujisho#388]
Recently I'm facing a problem in exporting to ankidroid.

There was no problem before but can't seem to make it work now!
Is this an issue with Android? 

![Screenshot_20240609_144812.jpg](https://github.com/lrorpilla/jidoujisho/assets/37247296/27943bae-c9a8-4e9d-bd9e-4fa1468a0f76)

**Comment by proy9714** [comment]
> Recently I'm facing a problem in exporting to ankidroid.
> 
> There was no problem before but can't seem to make it work now!
> Is this an issue with Android? 
> 
> [Screenshot_20240609_144812.jpg](https://github.com/lrorpilla/jidoujisho/assets/37247296/c20a77a6-3574-4249-a909-ba9290d852a8)

Maybe related to this?? 

![Screenshot_20240609_161702.jpg](https://github.com/lrorpilla/jidoujisho/assets/37247296/309b6894-5cd1-4630-b2a4-dfcef98715f7)

@lrorpilla

**Comment by brishtibheja** [comment]
You don't need to ping the dev before you even try the steps recommended. Also the first thing that you try is upgrading to newest version and that's what's written there. The newest version works with 2.17+ versions and you should upgrade to that one. One caveat: It has some known bugs and if you don't like the experience the alternative is to downgrade your Anki app. In any ways, this is a solvable problem. The toast is hinting to exactly that.

**Comment by proy9714** [comment]
> You don't need to ping the dev before you even try the steps recommended. Also the first thing that you try is upgrading to newest version and that's what's written there. The newest version works with 2.17+ versions of AnkiDroid and you should upgrade to that one. One caveat: It has some known bugs and if you don't like the experience the alternative is to downgrade your Anki app. In any ways, this is a solvable problem. The toast is hinting to exactly that.

I am using the latest version of the app and have also tried with the new pre-release version. The problem is persistent in both. I am using Ankidroid version 2.18.3.

**Comment by brishtibheja** [comment]
Your screenshot is from 2.8.9 version. Are you sure you used the 2.9.0-preview2? I am using that with 2.19alpha4 AnkiDroid. The latest version should work for 2.18.3 AnkiDroid too.

If you decide to downgrade your AnkiDroid version you'll need to downgrade to at least 2.16 as the app works for the previous v2 scheduler. I think some APIs were changed in 2.17 version along with v3 implementation.

**Comment by proy9714** [comment]
> Your screenshot is from 2.8.9 version. Are you sure you used the 2.9.0-preview2? I am using that with 2.19alpha4 AnkiDroid. The latest version should work for 2.18.3 AnkiDroid too.
> 
> If you decide to downgrade your AnkiDroid version you'll need to downgrade to at least 2.16 as the app works for the previous v2 scheduler. I think some APIs were changed in 2.17 version along with v3 implementation. 

Yes I updated to the preview and tried it. But I think the problem is with the Android version.....the release notes suggest Android 13 is the last supported. I'm using 14....can that be the issue?

@lrorpilla Could you please help??

**Comment by brishtibheja** [comment]
Did you try downgrading?

**Comment by proy9714** [comment]
> Did you try downgrading AnkiDroid?

Yup, doesn't work with 2.17 either.

**Comment by brishtibheja** [comment]
Oh God, I told you it won't work with 2.17+ but that also included 2.17 version. I told you in the last message to use 2.16 one.

**Comment by proy9714** [comment]
> Oh God, I told you it won't work with 2.17+ but that also included 2.17 version. I told you in the last message to use 2.16 one.

Hey works with 2.16!!! 

Thank you so much! Closing this issue.
