### ISSUE TITLE
Can't select Japanese audio in dual-audio files

### ISSUE THREAD

**Issue by DanTan3Machi** [lrorpilla/jidoujisho#39]
Just as the title says, I have a local dual-audio file that plays in English only although it has Japanese. I can't select the option for Japanese although it's already there. 
This how it looks
![Screenshot_20210724_215637_com lrorpilla jidoujisho](https://user-images.githubusercontent.com/87782307/126879854-8a9065f8-6f0c-44a9-a0a3-492f1b676221.jpg)

**Comment by lrorpilla** [comment]
I can't be of help without having the video file at hand. Thanks.

**Comment by DanTan3Machi** [comment]
Here's the episode download link if that works for you 
https://ddl.animeout.com/index.php?url=sv1.animeout.com/series/Completed/Fate%20Zero/Season%201/FateZero/[AnimeOut]Fate%20Zero-02%20(miniHD%20BD)(RareAMV)%20(UTW).mkv

**Comment by lrorpilla** [comment]
The link you've provided only has one audio track and it's in Japanese.

**Comment by DanTan3Machi** [comment]
Oh sorry that was the wrong link 
https://awoo.veronica.workers.dev/Fate%20Zero/[AnimeKaizoku]%20Fate%20Zero%20720p%20BD%20Dual%20Audio%20[dedsec]/02%20-%20False%20Start.mkv?r=rNKDAnkJ&tid=MEFNT3AtS1Z0aVZZcFVrOVBWQQ==&t=72a00&e=1627155

**Comment by lrorpilla** [comment]
I've replicated the issue with the new link and will investigate the solution.

**Comment by lrorpilla** [comment]
I have implemented the fix to this issue in [**0.25.10**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.25.10-beta) tested with the video you've provided and other test videos I have at hand.

See the relevant line in the release notes:
* Fixed an issue where in some videos, audio tracks did not change according to their proper index

With that, I am closing this issue.
