### ISSUE TITLE
A continuation to dual adio problem.

### ISSUE THREAD

**Issue by DanTan3Machi** [lrorpilla/jidoujisho#40]
This is a problem that arised after the recent update that was intended to fix a problem where selecting Japanese audio was not possible. 
A new problem arised. If I open the a video file that has dual audio the app crashes and exit. If I try to open the video from the file manger it works fine. 
This is a link for a video that has the problem. 
https://ouo.press/Tz0aKr
Note: other files that are mono-audio work just fine anywhere.
Take your time to fix it. It's a bit of a pain but I can still watch.
Thi

**Comment by lrorpilla** [comment]
I can't seem to reproduce this issue. Video seems to load just fine with dual audio.

This will need further investigation.

**Comment by DanTan3Machi** [comment]
I'm unable to do a screen recording. You see, the recording itself crashes when I open that file. 
I'm really confused because some episodes play normally and others, which are downloaded from the same sites don't work. Ep 16 and 17 for example crash the app, while 18 and 19 don't. Of course if I play from the file manager all episodes work without exception.

**Comment by DanTan3Machi** [comment]
I tried many other files and the problem didn't repeat itself. I think it might have been jusr those files.
