### ISSUE TITLE
2 Ideas - A Reading Mode, and Double-Tap to Pause/Unpause

### ISSUE THREAD

**Issue by vladz0r** [lrorpilla/jidoujisho#42]
Not sure if these are possible, but I feel like a reading mode would be pretty handy for people who want to learn to read.
Have it pause at the beginning of the line.

The pause button that appears when paused and works when the middle of the screen is tapped is ok, but I feel like setting a Double-Tap to pause would be much more useful, especially on tablets.
Not sure if it's doable with the current media player that is incorporated.

**Comment by lrorpilla** [comment]
I've considered these before and I have already attempted these ideas, unfortunately.

For the reading mode, this sort of play/pausing behavior is not stable enough for mobile VLC and the audio cuts out most of the time. Related to #17, this feature would be exactly that and bombard the player with play/pause calls.

The other idea might be possible, but I just don't much like adapting a design where a one tap is hiding and showing the interface, and two taps would be play/pause. This implementation is very akin to YouTube where it's impossible for the two gestures to intersect.

It may be convenient, but that's just what I've thought out from nitpicking the gestures.

**Comment by lrorpilla** [comment]
This is now possible in 2.8.0 with playback modes.
