### ISSUE TITLE
Can't export audio to anki 

### ISSUE THREAD

**Issue by DanTan3Machi** [lrorpilla/jidoujisho#43]
This doesn't happen to all video files, but in certain ones, audio can't be exported. The field doesn't even appear at the export pop up, but it does when I open it in anki.
https://ddl.animeout.com/index.php?url=slaine.animeout.com/series/Completed/Akatsuki%20no%20Yona/[AnimeOut]%20Akatsuki%20no%20Yona%20-%2001%20(720p-100MB)[FFF][Henz].mkv
This an example of a video the illicit this bug.

**Comment by lrorpilla** [comment]
This has been reported before. In this case, I can't really do much, likely ffmpeg is having trouble exporting the audio file. I try to cover all the bases, the solution I have given before is to just use a different source that cooperates, which isn't too hard given this only happens on occasion.

**Comment by DanTan3Machi** [comment]
As always, thanks for the quick reply. Sorry I didn't see the previous report. I'll do as you say and change to a different source.
Keep up the great work, king.

**Comment by lrorpilla** [comment]
Nah, no worries, the report wasn't made through a GitHub issue so there's no way to tell it was reported.

You seem to be streaming your sources instead -- if you have a PC and downloading is an option, might I suggest hosting a Plex server and instead using the Plex for Android app and host your video files through that? You can use it like a library on your phone for your shows and easily organise what you watch.

Just a suggestion, anyhow.
