### ISSUE TITLE
[Feature Request] Forvo audio and NHK Pitch Accent audios

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#44]
First of all, I'd like to tell you that I've done a factory reset on my phone and that I'm able to open local videos ever since. Thanks, again, for all the time you invested on my own personal issue.

I've been thinking about this request for a long time — you too might've thought about it, I suppose. My feature request is: automatically download and export Forvo audios to Anki and support for [NHK Pitch Accent audios that Migaku Japanese uses](https://mega.nz/file/yiwlDIaA#e1CQot7oapShNt36Ys5XVOPwf-DsGT8lkw9nMeVG18o). I believe that such feature would improve everybody's learning journey with Anki, plus it's a feature to make your project better.

(I've loving the manga feature. I was about to start reading mangas, and you made a tool for it)

**Comment by lrorpilla** [comment]
I am in hiatus so I cannot readily act on this feature request but I desire something like this. I will take this into consideration when I am less busy and will plan how exactly to implement such a feature over the long term.

**Comment by Feripe-a** [comment]
> I will take this into consideration when I am less busy and will plan how exactly to implement such a feature over the long term.

It will be something pretty darn good.

> This has been suggested before, but this has been in the backlog behind more important features which I have recently delivered.

Yes. Do the most important stuff first.

**Comment by lrorpilla** [comment]
A Forvo Audio enhancement has been added in [**1.1**](https://github.com/lrorpilla/jidoujisho/releases/tag/1.1).

If there are any follow-ups unaddressed in this issue, feel free to make them in a new issue.
