### ISSUE TITLE
[Feature Request] Resize/movable dictionary overlay for reader 

### ISSUE THREAD

**Issue by StinkyyTofu** [lrorpilla/jidoujisho#46]
First off, thank you for such an amazing app! I was looking for alternatives to Typhon and stumbled upon this gem :')

So far, the dictionary has been relatively easy to use, but I find that it does get in the way when looking up the definition/pronunciation of any kanji near the top of the screen. Being able to drag it around or resize the overlay would make it feel less intrusive and easier to use. Also, while less important, highlighting the current word/phrase being looked up would also be great (similar to Typhon).

**Comment by Feripe-a** [comment]
And child popups, like Yomichan, to easily look up words inside monolingual dictionaries. To do so, in the current version, you have to copy the word you want to look, then the first popup is closed, which makes it difficult to look up more words inside the monodict's def.

**Comment by lrorpilla** [comment]
A dictionary overhaul is well over due, but I am still working out the most fitting way that the layout should be on a mobile device.

I'm looking to take much inspiration from Yomichan as many users have desired -- how exactly I'll translate this into well working mobile UI/UX is still on the whiteboard.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant release notes.

- Dictionary results have received a complete and familiar makeover. You are no longer limited to a single active dictionary and may now view results from multiple dictionaries at once.
- You may now highlight text in dictionary definitions to perform recursive dictionary searches.
