### ISSUE TITLE
[Feature Request] White Mode 

### ISSUE THREAD

**Issue by Analogman2020** [lrorpilla/jidoujisho#49]
I really would love to use the reader and viewer aspects of this app with my ink reader but since it's only available in black, it's currently impossible to use. Would it be possible to have some sort of theme or light mode in the future by any chance?

Either way the app is amazing!

**Comment by Feripe-a** [comment]
It was implemented in the newest version.

**Comment by lrorpilla** [comment]
I am happy to share that I have officially implemented Chinese support in [**1.0.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/1.0.0).

See the relevant line in the release notes:

- 🎆 **[Throwing flashbang.](https://www.youtube.com/watch?v=Zp2EjsIYIhQ)** Users can now switch to light mode if they so wish, with the entire application adapting to theme.

With that, I am closing this issue.
