### ISSUE TITLE
Fr: pause playback when looking up a definition

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#5]
Typically when I look up a new word, I need some time to read the definition and understand the word in the context.

I think it would be a good idea to pause automatically when a lookup is done because of this.

Please consider this, and thanks for all your work!

**Comment by lrorpilla** [comment]
Sure. I'll get this covered tonight.

**Comment by lrorpilla** [comment]
I have implemented this feature in [0.13.1](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.1-beta).

See the relevant line in the release notes:
* **(New Feature) Focus Mode<sup><b>\*</b></sup>** - Users may now choose whether or not making a subtitle selection will pause the player. Focus mode will also resume playback on closing the definition if the query was made when playing.

With that, I am closing this issue.
