### ISSUE TITLE
Exporting to Ankidroid issue

### ISSUE THREAD

**Issue by ShiniXgami93** [lrorpilla/jidoujisho#50]
When I try to export to ankidroid, it exports the current snapshot but no audio. It only happens with one anime in specific. It works with the other ones. How can I fix this issue?

**Comment by T1CkShot** [comment]
Probably because of the file format try downloading the anime files from somewhere esle. though im not sure

**Comment by lrorpilla** [comment]
I'm archiving this issue as it appears to have been addressed, any followups are welcome. If there are any present concerns, feel free to reopen.
