### ISSUE TITLE
Is there a way to change the font or add other styles to the subs?

### ISSUE THREAD

**Issue by damiansh** [lrorpilla/jidoujisho#51]
I know the developer is on a break, so answer this whenever you have the time and you want to do so. 

Is there a way to change the font? Another family, or add bold, or even a background to the subs? I thought it would be useful for example for anime with hardsubs, I only found some episodes with hardsubs and it would ideal to be able to add a black background to t he subs, so it stands out from the hardsubs. 

Thanks in advance!

**Comment by lrorpilla** [comment]
Hi damiansh, you can use the blur widget under the audio and subtitle options. Cheers!

**Comment by damiansh** [comment]
It is just what I needed! I think I never noticed that option, thanks a lot for the quick response!

**Comment by lrorpilla** [comment]
I'm archiving this issue as it appears to have been addressed, any followups are welcome. If there are any present concerns, feel free to reopen.
