### ISSUE TITLE
2 bugs: 1) No dictionaries; 2) App won't open

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#53]
First of all, I'm glad you're back. You project is really good.

1)
I can't use dictionaries even though they were imported.
![Screenshot_20211127-173510_jidoujisho](https://user-images.githubusercontent.com/84395172/143722999-ff5a490a-76a3-40b5-91e0-05c1358e9c92.png)
When I look up something, it says that the term was not found:
![Screenshot_20211127-173600_jidoujisho](https://user-images.githubusercontent.com/84395172/143723025-0e2253f8-352b-4844-a2f6-347bef3316e7.png)
![Screenshot_20211127-173607_jidoujisho](https://user-images.githubusercontent.com/84395172/143723038-a0077c34-0a93-467b-bb2b-35ec3b186c03.png)
The dictionary is selected.
![Screenshot_20211127-173616_jidoujisho](https://user-images.githubusercontent.com/84395172/143723047-e7074188-94d9-4c73-b5e7-2c5ea768e5ad.png)

2)
I can't open the app anymore when I installed arm64-MAN.apk

**Comment by lrorpilla** [comment]
Hi Feripe, have you tried out the new hotfix? There might be bumps and bruises with this big release, so I'm trying to iron the problems over the next few hours/days. Let me know how you do with Hotfix 5.

**Comment by lrorpilla** [comment]
Oh, I should add. I expect a lot of existing users to be unable to find how to make their app function like the legacy version, especially now that you have to activate some enhancements to get the experience back.

Make sure you set your `Pitch Accent Export Diagrams` as **auto** and your reading dictionary widget as `Pitch Accent` if you want the old functionality back, and also `Bing Search` as **auto** if you want the auto image search back again. Everything is modular now, so you will have to set these up.

**Comment by Feripe-a** [comment]
> Let me know how you do with Hotfix 5.

Everything seems to work fine.
![Screenshot_20211128-074508_jidoujisho](https://user-images.githubusercontent.com/84395172/143764665-992b6c3b-f503-4168-8795-750284e6d7d6.png)
![Screenshot_20211128-074514_jidoujisho](https://user-images.githubusercontent.com/84395172/143764672-e530ea87-2ccf-428b-ae9b-4b8c69a8910f.png)

**Comment by Feripe-a** [comment]
> Everything is modular now, so you will have to set these up.

I've discovered how.

**Comment by Feripe-a** [comment]
I'll be on the look out for more issues.
This will be a big application in the future with support to all languages. I don't know any other app that does what Jidoujisho does.
