### ISSUE TITLE
[Feature Request] Reading Mode for Video Player

### ISSUE THREAD

**Issue by MrBigGay** [lrorpilla/jidoujisho#54]
Migaku and Language Learning with Netflix (only on PC) both have a reading mode. When enabled all it does is pause every time a new subtitle appears.

**Comment by MrBigGay** [comment]
Whoops sorry about that. I'm new and didn't realize you could see older posts. Turns out you already commented that it wasn't possible.

**Comment by lrorpilla** [comment]
This is now possible in 2.8.0 with playback modes.
