### ISSUE TITLE
App not installed on ARM chip

### ISSUE THREAD

**Issue by T1CkShot** [lrorpilla/jidoujisho#55]
My phone has a arm chip.The 1.0.0 doesn't have a armeabi-v7a download. is there any way around to install it?

**Comment by lrorpilla** [comment]
There is, I have to confess though, I just intentionally didn't include it to test and see if my users never use it. That architecture has to be included and built separately, so I was biding how much of the community needed it by omitting it and seeing how I went.

Now that you've asked, I'll probably get around to uploading it.

**Comment by T1CkShot** [comment]
Thanks for the upload. I'm looking forward to use the new features.
