### ISSUE TITLE
Certain video files and subs crash the app

### ISSUE THREAD

**Issue by KublaiKhan64** [lrorpilla/jidoujisho#56]
On my S10 certain videos regardless of file type crash the app the first time I launch them (for some it's every time) even if they're the same files as ones in the same series that work. Additionally often launching a subtitle will crash the app even if the rest in the series work. Sometimes relaunching the video, or waiting a but longer to load the sub helps but most often I just have to skip certain episodes and watch them in players where I can't mine

[ReinForce] Irozuku Sekai no Ashita kara 01 (BDRip 1920x1080 x264 FLAC) is the file I encountered this with most recently as well as the [Nekomoe kissaten][Irozuku Sekai no Ashita kara subs

**Comment by lrorpilla** [comment]
I'll take a look at this some time.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that your issue is still present in 2.0, feel free to open.
