### ISSUE TITLE
Reloading the file

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#58]
This issue is related to subtitles and pausing the video. It can happen in three different ways. I was able to reproduce one [on this video](https://streamable.com/tjommi).
1) spamming the pause button. I found this error when I was trying to listen to different sections of the anime while imaging the words.
2) selecting dialogues. It happened two times, but I was not able to reproduce it on video.
3) switching between subtitles (jp > en; en > jp). I tried a few times and was not able to reproduce it.

**Comment by Feripe-a** [comment]
I hope I successfully described this issue.

**Comment by lrorpilla** [comment]
A fix for the pause button issue has been implemented with Hotfix 14. If you can accurately and properly reproduce the other scenarios, I welcome you to re-open the issue.
