### ISSUE TITLE
Turning off subtitles

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#59]
I've just found a bug when you turn off subtitles. The displaying line when you turn subs off still appears on the screen as if subs weren't off. As always, [I have recorded a video](https://streamable.com/qgsdcn).

**Comment by lrorpilla** [comment]
Fixed in Hotfix 16. I'd like to thank you for the thoroughness of your reports, they are very helpful in helping me get down to the bottom of things. If you have any follow-up issues, you are welcome to re-open.

**Comment by Feripe-a** [comment]
You're fast as always.
Thanks for your kind words. I'll be on the look out for more things to improve this amazing application.
