### ISSUE TITLE
Cannot use media keys to pause video player anymore

### ISSUE THREAD

**Issue by dkaknbk** [lrorpilla/jidoujisho#60]
In the previous versions I always used the media play/pause key to pause video files at will in case I needed to read the subtitles again. However, in the new version, the media keys ignore the jidoujisho application and instead of pausing the current video, they start playing audio from the last application I used before using jidoujisho instead.

**Comment by lrorpilla** [comment]
Yeah, I hadn't implemented this back yet, because I didn't like the hacky way it was implemented in legacy. I'll definitely reimplement it some time.

**Comment by lrorpilla** [comment]
This is implemented in 1.0 Hotfix 18. If you have any follow-ups, you're welcome to re-open.
