### ISSUE TITLE
The last version is crashing and not opening up anymore while I read light novels

### ISSUE THREAD

**Issue by Astarka06** [lrorpilla/jidoujisho#62]
I'm reading a light novel that's less than 90k characters on in JPN and after a while reading it crashes. I can only get it back after clearing data/cache. Restarting my phone also doesn't work. I have the an older version installed on my phone tho, but iirc it says that that's fine. My phone is a galaxy a02s android 11.

**Comment by lrorpilla** [comment]
This issue has been described before to me, can you describe to me more about how to exactly replicate the crash?

**Comment by lrorpilla** [comment]
I'd like to confirm that you were on 1.0.18 or the latest version when it happened. As you may know, every word searched on jidoujisho results to a dictionary entry added to history. If you long-press on history, you will see a context option that returns you to exactly where you found a word, either from a video or book, to the exact duration or scroll position.

I fixed an issue with TTU a few days ago where with every dictionary definition tapped, I accidentally included the thumbnail information of the book - all in base64 String with each history item. It is possible you were in an older version of 1.0 below this hotfix and your history got bloated to a point where launching the app would initialised the entries -- but they were too much, causing a memory leak and then a crash. 

That's my theory, and it would be ruled out if you were on 1.0.18 when it happened, after I applied the fix.

**Comment by Astarka06** [comment]
> 



> I'd like to confirm that you were on 1.0.18

Version 1.0.0
I believe it crashed after I read for a while doing look ups, iirc it crashed right after a look up. The app storage is 510mb currently, I made sure it had all permissions. Do you want me to recreate the crash?

**Comment by lrorpilla** [comment]
What's the version number when you clear cache? It should be 1.0.18, if not, uninstall your current version and try downloading and installing the latest version.

**Comment by lrorpilla** [comment]
With no response, I believe this issue has been addressed with the information above.

You are welcome to reopen the issue with any follow-ups.
