### ISSUE TITLE
ttu-ebook.web.app is different and I can't tap words and get def popups 

### ISSUE THREAD

**Issue by Astarka06** [lrorpilla/jidoujisho#69]
I can only do lookups if I long press it and manually select the word I want to know. Anyone else having that? If there's a workaround this I'd like to know ty.
Lastest version btw

**Comment by lrorpilla** [comment]
Latest version is 1.1.8. Anything less isn't updated for the new ttu, which version are you on?

**Comment by lrorpilla** [comment]
Assume previous comment has addressed this query, with no further info, closing

Feel free to reopen
