### ISSUE TITLE
Don't confirm ending playback when video has ended

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#7]
I figured I'd open some issues that seem like low hanging fruit.

When the video has ended and I navigate back to leave it, I'm still asked if I want to leave.

Kind of makes sense but idk if it would be nice to just leave without asking in this case.

**Comment by lrorpilla** [comment]
I have implemented this feature in [0.13.1](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.1-beta).

See the relevant line in the release notes:
* The player will **no longer show the 'End Playback' message if the video has already ended**<sup><b>\*</b></sup>

With that, I am closing this issue.
