### ISSUE TITLE
How do you change font? 

### ISSUE THREAD

**Issue by damiansh** [lrorpilla/jidoujisho#71]
In the subtitle options it has font name as field, and an icon there redirects you to google fonts. How do you install and change fonts in Jidoujisho then? Thanks in advance!

**Comment by lrorpilla** [comment]
You can't install fonts, have to pick a font available in Google Fonts under Japanese and match the name, case-sensitive

**Comment by damiansh** [comment]
I have tried that, for example there is a font called Murecho, I put that instead of the default Roboto and press set but it doesn't close and save the settings
