### ISSUE TITLE
Bug when dealing with blank sub lines in subtitles 

### ISSUE THREAD

**Issue by damiansh** [lrorpilla/jidoujisho#72]
**Jidojisho version:** 1.1.8
**My device:** Samsung Glaxy Tab S7 Plus
**Anime example:** Detective Conan Episode 0633
**Subtitle:** https://drive.google.com/file/d/1_FjupqQ1vHFM5715qA2thgAm-8BsOIgS/view?usp=sharing

I am not sure how often you will find blank lines in subtitles while immersing but just in case it's something that can regularly happen I decided to post the issue.

On the show Detective Conan which I am watching now, there are some blank lines for some reason, and this apparently messes with line that goes after that blank one. 

Basically, it shows the next line with its time in the timming of the blank line.

I am bad explaining so here you have an screenshot: 
![image](https://user-images.githubusercontent.com/44991000/147430157-5929a711-f3b8-434d-ba05-54788d824319.png)

After checking the sub, there is a blank line just before that one:
![image](https://user-images.githubusercontent.com/44991000/147430233-b302f535-a774-4b7f-bd30-c80214401488.png)

The same thing happens in the next instance of a blank line: 
![image](https://user-images.githubusercontent.com/44991000/147430211-d5c9d829-bd4e-4a47-aff5-cbf155b89e11.png)

In the following link you have the video of the problem:

https://www.youtube.com/watch?v=bA-4VAtQazo

I have included the srt file just in case you want to take a look.

Thank you in advance, and let me know if you have any questions!f

**Comment by lrorpilla** [comment]
Changing the SRT parser might be necessary for this one, will look into the edgecases

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that your issue is still present in 2.0, feel free to open.
