### ISSUE TITLE
[feature request] Homescreen app shortcuts

### ISSUE THREAD

**Issue by Sakusuke** [lrorpilla/jidoujisho#73]
I'm reading a book with the app, it's a really great experience. But I would like to open it more easily. The method to make a shortcut could be a long press on the app icon and then choosing from recent media to make a shortcut of (see GitHub app for reference). Or in the long press menu of the media inside the app itself (see pic)
![IMG_20211229_232520.jpg](https://user-images.githubusercontent.com/64757785/147708010-2e4008fa-632c-4137-84c2-52f9a4396731.jpg)

**Comment by lrorpilla** [comment]
I feel that this is more of a nice-to-have rather than a must.
