### ISSUE TITLE
Regarding subtitle in .mkv

### ISSUE THREAD

**Issue by Renzodasu** [lrorpilla/jidoujisho#74]
No subtitle will appear if you select a subtitle that is within the .mkv file and not the external ones. And also external subtitles are floating above abnormally, it is not in its natural position below.

**Comment by lrorpilla** [comment]
I need a picture - for subtitles, they are intended not hug the bottom so it makes space for the bar below. 

What video are you playing? I need to know what kind of subtitles the video has. If it has optical-based subtitles, those are not supported.

**Comment by Renzodasu** [comment]
![20220106_191326](https://user-images.githubusercontent.com/97201276/148375070-b85692cb-a9bd-4ef2-be23-9f4805c144fb.jpg)
![20220106_191432](https://user-images.githubusercontent.com/97201276/148375078-4a18a495-50e2-4936-b19d-e32544cd30f9.jpg)
![Uploading Screenshot_2022-01-06-19-02-42-337_app.lrorpilla.jidoujisho.jpg…]()
![Uploading Screenshot_2022-01-06-19-03-14-620_app.lrorpilla.jidoujisho.jpg…]()
![Uploading 20220106_191721.jpg…]()
![Uploading 20220106_191930.jpg…]()
![20220106_190836](https://user-images.githubusercontent.com/97201276/148375026-7b6d2d3f-d0b9-41fa-92fc-d74114c38999.jpg)

Same video file

**Comment by Renzodasu** [comment]
![Uploading 20220106_191326.jpg…]()
![20220106_191432](https://user-images.githubusercontent.com/97201276/148375479-e38ab01b-0611-4498-ab98-1010b2dadae9.jpg)
![Uploading Screenshot_2022-01-06-19-02-42-337_app.lrorpilla.jidoujisho.jpg…]()
![Uploading Screenshot_2022-01-06-19-03-14-620_app.lrorpilla.jidoujisho.jpg…]()

**Comment by Renzodasu** [comment]
![Uploading 20220106_191326.jpg…]()

**Comment by Renzodasu** [comment]
![Uploading 20220106_191432.jpg…]()

**Comment by Renzodasu** [comment]
![Uploading Screenshot_2022-01-06-19-03-14-620_app.lrorpilla.jidoujisho.jpg…]()

**Comment by Renzodasu** [comment]
![Uploading Screenshot_2022-01-06-19-02-42-337_app.lrorpilla.jidoujisho.jpg…]()

**Comment by Renzodasu** [comment]
![20220106_191326](https://user-images.githubusercontent.com/97201276/148378476-b67066b1-e455-4ebc-9d9d-da0154f82999.jpg)
![20220106_191432](https://user-images.githubusercontent.com/97201276/148378480-7247b6af-9d4b-4c83-9cdd-e6fe9b4cb4de.jpg)
![Screenshot_2022-01-06-19-02-42-337_app lrorpilla jidoujisho](https://user-images.githubusercontent.com/97201276/148378752-f4d4adf8-a618-457d-a0cc-5cf99aba4966.jpg)
![Screenshot_2022-01-06-19-03-14-620_app lrorpilla jidoujisho](https://user-images.githubusercontent.com/97201276/148378773-7d573519-b023-4ceb-a86f-9ef8f2e559c3.jpg)

**Comment by Renzodasu** [comment]
I think adding an option whether a user will prefer adding a gap below or not would be great

**Comment by Feripe-a** [comment]
> ![20220106_191326](https://user-images.githubusercontent.com/97201276/148378476-b67066b1-e455-4ebc-9d9d-da0154f82999.jpg)

This happens to me a lot.

**Comment by lrorpilla** [comment]
Your imported subtitles are read by the player after the video has loaded, so it's natural, I need a picture of the gap 

I intentionally didn't add it so the user clicking on subs doesn't get confused with the subs changing places when the menu appears

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the following line in the release notes.

- The current subtitle's padding now adjusts to whether or not the bottom menu is currently visible.
