### ISSUE TITLE
Crashed when tap load file button (the arrow one) on reader on Huawei tablet, and cannot open links on reader.

### ISSUE THREAD

**Issue by HQYang1979** [lrorpilla/jidoujisho#76]
It is such a brilliant app, but it crashed when tap load file button (the arrow one) on reader on Huawei tablet, and cannot open links on reader.

Works great on Player.

Cannot load images on Viewer.

**Comment by HQYang1979** [comment]
I installed 0.26.3beta, the reader works fine.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that your issue is still present in 2.0, feel free to open.
