### ISSUE TITLE
Extremely slow look up

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#79]
Recently, looking up words was taking a lot of time, around one minute. I thought it was due to my phone. But today I accidentally fixed that issue.
The source of this bug (???) is the Dictionary History. Somehow if you keep looking up words without cleaning the Dictionary History, look-up results will be extremely slow. I'm not 100% sure but I say it's the Dictionary History because when I have accidentally cleaned it, look-ups went to their normal speed — almost instantaneous sometimes.
I haven't cleaned my Dictionary History since last month.

**Comment by damiansh** [comment]
It happened to me too, but what I did was to delete all the app's data and set up again.

If it starts to slow down I will try deleting the dictionary history to see if that fixes it. Though for the moment it has been working fine since that wipe.

**Comment by Feripe-a** [comment]
> delete all the app's data and set up again
Yes. This works as well. So we can guess that the app stores something that makes look-ups slow.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant line in the release notes.

- The dictionary search algorithm has been overhauled, with dramatic improvements to query speed, performance and results.
