### ISSUE TITLE
Pause video when bluetooth headphone pause button is pressed

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#8]
My bluetooth headphones have a pause+resume button and two volume controls. The volume controls work right now, but the pause button does nothing.

If I use the same headphones with Netflix or YouTube (vanced), the video is paused and resumed like one would expect.

**Comment by lrorpilla** [comment]
I have implemented this feature in [0.13.1](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.1-beta).

See the relevant line in the release notes:
* **(New Feature) Headset Play/Pause<sup><b>\*</b></sup>** - Users will now be able to play and pause the video with their headset controls

With that, I am closing this issue.

**Comment by lrorpilla** [comment]
I am aware of an issue where this functionality does not seem to persist if the user changes apps or performs any lifecycle changes (sleep).

The `audio_service` I'm using seems to terminate leading to the headset button callbacks unable to call. I'm reopening this issue.

**Comment by lrorpilla** [comment]
I have implemented a fix for this in [0.13.3](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.3-beta).

See the relevant line in the release notes:
* Fixed an issue where switching tasks or changes to the app life cycle **invalidating headset controls**

With that, I am closing this issue.
