### ISSUE TITLE
[Feature Request] Streamline Mining Process

### ISSUE THREAD

**Issue by cademcniven** [lrorpilla/jidoujisho#81]
I'll preface by saying I haven't spent a large number of hours using this app, so it's possible these features already exist and I'm just unaware of them.

To me, the speed at which you can make Anki cards is incredibly important for a good mining/immersion set up. I won't even bother if it's too slow or requires too much effort. From what I can tell, the jidoujisho mining workflow has a few areas that could significantly improve mining speed and make the process a lot more seamless.

Specifically I'm gonna be referring to the mining process for videos, but it might apply to reader/viewer as well idk.

It's my understanding that you currently have to open the card creator to mine a word. Additionally, once you're there, you have to select what word in the sentence you want to be the target word, as well as type its definition.

Instead of that, when I view a definition while watching the video, I think there should be a button on the popup window that adds the card. It will automatically grab that word + definition + sentence + pic + audio with 1 button. Of course, the card creator will still be an option for people that want to get more detailed, but for quick automated mining this would be far superior imo.

For the audio field, it would be nice if I could provide a source once and it would auto pull audio every time. Specifically, just like mining with Yomichan, if it could just pull the japanesepod101 audio whenever I mine, that would be great (of course, that's in addition to the sentence audio, not a replacement).

It would also be nice if a specific dictionary could be auto added to the "Extra" field. Specifically, I'd like to use a pitch accent dictionary and and have the pitch accent of the word get auto-added to the extra field whenever I mine with this workflow.

Again, I might just be unaware of these features due to not using the app enough, but if they're *not* implemented, I think it could be a real game changer. It would allow people to mine even better cards with just a single button press.

**Comment by lrorpilla** [comment]
I can say I have plans to significantly improve things in this regard, but they won't come into fruition so soon and it will be some time till they're ready.

I can't share those plans directly but working on mining and making it friendlier and streamlining the process is something I'm whiteboarding at the moment.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant lines in release notes.

- Quick Actions allows users to quickly perform tasks for a certain dictionary result. These may be set while editing the enhancements of the Card Creator. The new Quick Action system provides developers with a layer of abstraction for easily adding more actions should they wish to do so.
- Card Creator - Allows users to pick a word, show a dictionary result and then open the Creator with prefilled information corresponding to the word, complete with Reading, Meaning, Image, Audio and more.
- Instant Export - Allows users to quickly export the word, and have the fields be prefilled according to the word and the user's auto enhancements, without opening the Card Creator.
