### ISSUE TITLE
[Feature Request] Changing field order

### ISSUE THREAD

**Issue by damiansh** [lrorpilla/jidoujisho#82]
First of all, I have to say I really love this app and probably I would have a harder time sentence mining from anime and dramas without this one, thanks a lot!

I recently also started to mine using yomichan from visual novels, the problem is that apparently yomichan uses the first field to check if a word is a duplicate. So I changed the field order, putting word as the first one and sentence as the second one.

Now if I add cards from jidoujisho, these get swapped, so I need to changed them before or after adding the cards to Anki. 

So I was wondering, is there a way to change this order in Jidoujisho? If not, it would be nice to have that freedom to decide what field goes where, so the card type can be more customizable I guess.

**Comment by lrorpilla** [comment]
There isn't a way built in but being able to customise the export format is something that is highly wanted and something I'm looking to do,

I intend to go big the next time I do a major release, and I want to address some major wants and needs to the source code,

Given I'm busy and employed these days, something significant is going to remain in the making for some time, but this is definitely a top priority

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

- Fields that are shown in the Card Creator may now be reordered and enabled according to user preference. The new Field system provides developers with a layer of abstraction should they wish to add a new exportable field that, for example, can be auto-generated upon selecting a certain word.
- Fields may be hidden away from view and collapsed should the user wish to reduce clutter in the Card Creator.
- Profiles allow users to switch between paradigms, and change Card Creator and Anki export preferences with the tap of a button.
- Each profile corresponds to a certain Anki model and mapping a user can set.
- Enhancements, Fields and Quick Actions are tied to Profiles. Users may use this to quickly switch between use cases.
