### ISSUE TITLE
[Feature suggestion] Consider using manga-ocr

### ISSUE THREAD

**Issue by WilsonNet** [lrorpilla/jidoujisho#83]
Nice work on jidoujisho, really useful.
Recently I've been experimenting with a new OCR, called [manga-ocr](https://github.com/kha-white/manga-ocr), and in my experience, it has more than 99% precision rate. It's really out of this world.

**Example** (the page selected was totally random):

https://user-images.githubusercontent.com/25280488/153520966-be319a80-228a-4a7e-a783-807635771abd.mp4

**Comment by lrorpilla** [comment]
I'm looking into this, will have to hook it into Chaquopy if I ever make use of it since it uses Python.

**Comment by WilsonNet** [comment]
> I'm looking into this, will have to hook it into Chaquopy if I ever make use of it since it uses Python.

Nice, just a Heads up. I was experimenting with manga and it was ultra-reliable. Tried to experiment with Civilization 6 yesterday and it was not that good. Sharex OCR is better for games (I don't really know what they use).

Maybe it's better to restrain it to mangas, like the name implies.

**Comment by kha-white** [comment]
Hi, manga-ocr author here. I'm glad to see the interest in this project, and would love to see it integrated with jidoujisho!

One alternative to Chaquopy would be to export model to onnx format and run on Android using onnxruntime.

https://huggingface.co/docs/transformers/serialization
https://onnxruntime.ai/docs/tutorials/mobile/

The hard part here is the onnx export, I think it _should_ be possible, but might be tricky. I was meaning to try it myself at some point, but I'm not sure when I will find time for that. There's also some [Python logic](https://github.com/kha-white/manga-ocr/blob/master/manga_ocr/ocr.py) which would need to be ported, but it's rather lightweight so it shouldn't be a problem.

Just wanted to mention this, I don't actually know if it's a better option than Chaquopy (probably depends on how well Chaquopy can deal with Pytorch and Huggingface dependencies).

**Comment by lrorpilla** [comment]
Hey, @kha-white. I was thinking of contacting you about this by e-mail, then I remembered that you had already reached out some time ago.

I cut the Viewer from my 2.0 release because I wanted to try integrating your work and using it on Android but I had trouble running it with Chaquopy (there are some issues in their repo related to fugashi and pyclippers (this was the one that errored out for me ultimately).

To be honest I'm not at all literate or have ever gotten hands on with machine learning software (though I'd like to use this opportunity to do so). If you can spare time, I'd like to work together to make this a possibility.

**Comment by PainterHalver** [comment]
Would really love to see this in the app!

Would it be hard to implement the screen cut and paste feature like in manga-ocr, supposing that ocr api is working already?

**Comment by mathewthe2** [comment]
> The hard part here is the onnx export

Export of VisionEncoderDecoder models to ONNX has now been merged to huggingface.

https://github.com/huggingface/transformers/pull/19254

I ran the following command and the files were produced without error:

`python -m transformers.onnx --model=models--kha-white--manga-ocr-base/ --feature=vision2seq-lm onnx/ --atol 1e-3`

I haven't tried doing inference yet, but it seems feasible.

**Comment by kha-white** [comment]
Yeah I've tried that too, export seems fine, but inference is not as straightforward since you need to do a beam search or something similar. Definitely doable, but requires some work.

**Comment by lrorpilla** [comment]
I was wondering, would **[this](https://pub.dev/packages/pytorch_mobile)** or **[this](https://pub.dev/packages/flutter_pytorch)** be of any use? I have a lot of spare time at the moment to study up on this, but ML isn't my field at all though, I could use some guidance on what I might need to get this to work.

**Comment by lrorpilla** [comment]
Closing as per #75.

**Comment by mathewthe2** [comment]
@arianneorpilla 

Following [HighLiuk's implementation in Python](https://github.com/kha-white/manga-ocr/issues/45#issuecomment-2320234358), I managed to get the same results using the same single file model (460.9MB). I have only tried it on the iPhone emulator for now, but I'll confirm if it works with my phone later. I wonder if the entire model has to be loaded into memory every time we infer.

```dart
import 'package:onnxruntime/onnxruntime.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'dart:ui' as ui;
import 'dart:typed_data';
import 'package:image/image.dart' as img;

  Future<List<double>> imageToFloatTensor(ui.Image image) async {
    final imageAsFloatBytes =
        (await image.toByteData(format: ui.ImageByteFormat.rawRgba))!;
    final rgbaUints = Uint8List.view(imageAsFloatBytes.buffer);

    final indexed = rgbaUints.indexed;
    return [
      ...indexed.where((e) => e.$1 % 4 == 0).map((e) => e.$2.toDouble()),
      ...indexed.where((e) => e.$1 % 4 == 1).map((e) => e.$2.toDouble()),
      ...indexed.where((e) => e.$1 % 4 == 2).map((e) => e.$2.toDouble()),
    ];
  }

  Uint8List resizeImage(Uint8List inputImage, int width, int height) {
    // Decode the image from Uint8List
    img.Image? originalImage = img.decodeImage(inputImage);

    if (originalImage == null) {
      throw Exception('Failed to decode the image.');
    }

    // Resize the image to the target size (224x224)
    img.Image resizedImage =
        img.copyResize(originalImage, width: 224, height: 224);

    // Convert the resized image back to Uint8List (RGB format)
    return Uint8List.fromList(img.encodePng(resizedImage));
  }

  Future<List<String>> _loadVocab(String vocabFilePath) async {
    // Load the vocabulary file from the assets
    final String vocabFileContent =
        await rootBundle.loadString("assets/models/vocab.txt");

    // Split the content by lines
    List<String> vocab =
        vocabFileContent.split('\n').map((line) => line.trim()).toList();

    return vocab;
  }

  Future<OrtValueTensor> _preprocess(ByteData imageData) async {
    final codec = await ui.instantiateImageCodec(
      imageData.buffer.asUint8List(),
      targetHeight: 224,
      targetWidth: 224,
    );
    final image = (await codec.getNextFrame()).image;

    final rgbFloats = await imageToFloatTensor(image);
    for (int i = 0; i < rgbFloats.length; i++) {
      rgbFloats[i] = (rgbFloats[i] / 255.0) - 0.5; // Normalize pixel values
      rgbFloats[i] = (rgbFloats[i] - 0.5) / 0.5;
    }
    final inputOrt = OrtValueTensor.createTensorWithDataList(
        Float32List.fromList(rgbFloats), [1, 3, 224, 224]);
    return inputOrt;
  }

  List<int> _generate(
      OrtValueTensor inputOrt, OrtSession session, OrtRunOptions runOptions) {
    List<int> tokenIds = [2]; // Start with token ID 2.
    for (int i = 0; i < 11; i++) {
      // Prepare the input tensor for token IDs.
      final tokenIdsBatch = List<List<int>>.from([tokenIds]);
      final tokenIdsOrt = OrtValueTensor.createTensorWithDataList(
          Int64List.fromList(tokenIdsBatch.expand((e) => e).toList()),
          [1, tokenIds.length]);

      // Define the inputs to the session.
      final inputs = {
        'image': inputOrt,
        'token_ids': tokenIdsOrt,
      };

      // Run the ONNX session.
      var outputs = session.run(runOptions, inputs, ['logits']);

      final OrtValue? logitsOrt = outputs[0];
      if (logitsOrt == null) {
        throw Exception('Failed to retrieve logits.');
      }

      final List<List<List<double>>> logitsNested =
          logitsOrt.value as List<List<List<double>>>;

      final List<List<double>> lastLogits = logitsNested[0];
      final List<double> logits = lastLogits[lastLogits.length - 1];

      int tokenId = 0;
      double maxValue = logits[0];
      for (int j = 1; j < logits.length; j++) {
        if (logits[j] > maxValue) {
          maxValue = logits[j];
          tokenId = j;
        }
      }

      tokenIds.add(tokenId);

      if (tokenId == 3) {
        break; // Stop if the token ID is 3.
      }
    }
    return tokenIds;
  }

  Future<String> _decode(List<int> tokenIds) async {
    String text = "";
    List<String> vocab = await _loadVocab('assets/vocab.txt');
    for (final tokenId in tokenIds) {
      if (tokenId < 5) {
        continue;
      }
      text += vocab[tokenId];
    }
    return text;
  }

  void _infer() async {
    OrtEnv.instance.init();
    final sessionOptions = OrtSessionOptions();

    final rawAssetFile = await rootBundle.load("assets/models/model.onnx");
    final bytes = rawAssetFile.buffer.asUint8List();
    final session = OrtSession.fromBuffer(bytes, sessionOptions);
    final runOptions = OrtRunOptions();

    ByteData imageData = await rootBundle.load('assets/test/00.jpg');
    OrtValueTensor inputOrt = await _preprocess(imageData);

    final tokenIds = _generate(inputOrt, session, runOptions);

    final answer = await _decode(tokenIds);
    print(answer);

    inputOrt.release();
    runOptions.release();
    sessionOptions.release();
    OrtEnv.instance.release();
  }
```
