### ISSUE TITLE
[Feature suggestion] Audio Padding + Clipboard / Unnecessary Character Trim + Pleco Chinese Integration 

### ISSUE THREAD

**Issue by lukepham-dev** [lrorpilla/jidoujisho#84]
First off, thank you so much for making this software, it's been a massive help to me and such a useful thing to help me be able to sentence mine for Chinese on my phone. Now as to the feature requests.

As per title, the thing that would really help are these. Most of these features are from mpvacious, where the settings can be adjusted in the .lua or .conf files. Apologies for making it into a single feature request log. Let me know if it's better as separate titles:

1) Audio padding: Some subtitle files I use are not precisely timed and a lot of the time the audio is getting cut off because of this. What I have to do at this point is include the next or previous line to capture that audio. 

2) Clipboard trimming in terms of removing unnecessary characters from strings. The reason why this is useful is because subtitles tend to have spaces, and the Chinese Support plugin I use for Anki doesn't work if there are spaces in them. At the moment I have to manually look through the cards and remove the spaces.

3) Pleco Support: For Chinese, Pleco is an extremely comprehensive dictionary application that almost every Chinese learner is or should be using. What I'm requesting is for an option to copy and paste the subtitle line selected and open it up in the Pleco application. Currently I am using Pleco's Screen Reader to look up words in the subtitles, mainly because unfortunately the dictionaries used aren't quite as detailed nor as good as parsing the words in the sentence.

Please let me know if more clarification is needed. Thanks again for all the hard work!

**Comment by lrorpilla** [comment]
Hi, lukepham

You can already adjust subtitle timing in one of the options under the player, you'll be able to adjust and expand the window of the subtitle audio, you can also include multiple lines by using the transcript and holding on another line

For clipboard trimming, I don't have such postprocessing steps for text but maybe a simple extension may do,

You may also share subtitle text as on option under the app, so any app that supports text sharing can receive it,

I am happy that people are using this for languages other than Japanese, it's good to see it being put to use for Chinese.

**Comment by lukepham-dev** [comment]
> Hi, lukepham
> 
> You can already adjust subtitle timing in one of the options under the player, you'll be able to adjust and expand the window of the subtitle audio, you can also include multiple lines by using the transcript and holding on another line.
> 
> For clipboard trimming, I don't have such postprocessing steps for text but maybe a simple extension may do,
> 
> You may also share subtitle text as on option under the app, so any app that supports text sharing can receive it,
> 
> I am happy that people are using this for languages other than Japanese, it's good to see it being put to use for Chinese.

Thanks for this! I can't believe I didn't spot that earlier, you're right in that there is already audio padding, along with the ability the subtitle line to external apps like Pleco.

For clipboard trimming, it's pretty much for any spaces that are in the line, it just removes the spaces and goes from there. As said before, I'm just basing my feature requests over what is already in mpvacious and then asking for it to be here. 

Yes, it is highly applicable to pretty much any other language, the reason it's great is because it can easily create cards with audio and images no matter what language it is to then  process on the computer and use whatever plugins there. There are some other issues I'm having but I'll write it in a different issue to keep it organised.

Thank you again. Like mentioned, if clipboard trimming can be integrated, that would be immensely helpful as it save me from going into each line and trying to remove spaces manually. Keep up the great work!

**Comment by lrorpilla** [comment]
Closing as I believe this issue has been addressed. If there are any other concerns, feel free to re-open.
