### ISSUE TITLE
Big files support????

### ISSUE THREAD

**Issue by baselmagdy2** [lrorpilla/jidoujisho#86]
Hello,I have a huge 11 GB movie, my phone can handle it on other players , jidoujisho on the other hand lags? Idk if this is fixable

**Comment by lrorpilla** [comment]
I need more information on your device and the exact circumstance of what is happening to determine what to do and how to action this bug. If possible, please provide me with a video of what is going on so I can see what exactly is the problem.

**Comment by baselmagdy2** [comment]
Hello, my phone is an oppo f7 ,the video just freezes or is lagging very hard I'm sure my phone can handle it as other players can run it 
https://files.catbox.moe/oxh7v6.mp4 video

**Comment by Feripe-a** [comment]
Does my issue #68  relates to this one?

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that your issue is still present in 2.0, feel free to open.
