### ISSUE TITLE
[Feature Request] Add ability to select text and search dictionary using jidoujisho

### ISSUE THREAD

**Issue by kuroahna** [lrorpilla/jidoujisho#87]
In the Kaku app, they have this feature where you can select text and look up words in the dictionary. It would be nice if there was something similar in jidoujisho. The downside with using Kaku is that it's limited to JMDict dictionary only. Being able to use yomichan dictionaries (ie monolingual dictionaries) with jidoujisho is great, but having to copy and paste the word into the app each time instead of selecting text is a bit cumbersome.

![image](https://user-images.githubusercontent.com/85209455/156245302-b9d5b7cf-7e84-46db-92d7-3f873a758086.png)

![image](https://user-images.githubusercontent.com/85209455/156245827-3487497d-d7a7-499a-97f1-603216fa6b4c.png)

See video at 1:55 https://www.youtube.com/watch?v=SfF5GKs7yJk

**Comment by lrorpilla** [comment]
This is something that I've tried to do but it came out as buggy, will want to get it right in the future though. For now, sharing text to jidoujisho is the same. I want to make it better so it just doesn't result to using the creator and let you search in the dictionary though.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant release notes.

- Dictionary results have received a complete and familiar makeover. You are no longer limited to a single active dictionary and may now view results from multiple dictionaries at once.
- You may now highlight text in dictionary definitions to perform recursive dictionary searches.
