### ISSUE TITLE
furigana spacing makes the word search not work

### ISSUE THREAD

**Issue by foss1234** [lrorpilla/jidoujisho#88]
hello when ever there is furigana on a word it doesn't search it probably i have managed to find a solution on yomi chan but idk if it's implementable on the app [this + the + non japanese character setting](https://github.com/ttu-ttu/ebook-reader/issues/28 )
![Screenshot_2022-03-05-14-58-37-26_72b61445d99b48197be28ce805d10c83](https://user-images.githubusercontent.com/101003172/156884328-05236161-c226-47e0-b8a4-8ac2083c5f44.jpg)

**Comment by T1CkShot** [comment]
#30 This might help? I'm not sure though.

**Comment by foss1234** [comment]
@T1CkShot i can not find an option to add filters

**Comment by lrorpilla** [comment]
This filter does not exist in Reader mode. Will look into it in the future.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that this issue is still present in the new version, feel free to open.
