### ISSUE TITLE
Video player shenanigans 

### ISSUE THREAD

**Issue by Waffelatte** [lrorpilla/jidoujisho#89]
I have a OnePlus 9 running Android 12, and the newest release of oxygenOS as of this post, if that's relevant. Version 1.1.11 arm64
Now, admittedly I only have a sample-size of two .mkv videos, but here are the issues I've encountered:

Player will be stuck on loading 80% of the time I try to start a video. Seems to be more frequent when starting a video, that's continuing from a previous session.
Restarting the app fixes it sometimes, but that may just be false perceived correlation.
![Screenshot_2022-03-09-08-34-46-78_72b61445d99b48197be28ce805d10c83](https://user-images.githubusercontent.com/101220057/157394221-bf4ecefa-c380-423f-b668-d814dfd1e0df.jpg)

It seems like it always stays stuck on loading when 'definition focus mode' is turned on. Might just be previous issue with bad luck in the mix.

Sometimes starting a video works, but the screen is black. Leaving the video and going back in fixes it sometimes.
![Screenshot_2022-03-09-08-34-23-16_72b61445d99b48197be28ce805d10c83](https://user-images.githubusercontent.com/101220057/157394326-3eb7186d-75d0-40a7-8f94-7465787b8174.jpg)

Using the transcript navigation freezes the image. Audio and subs keep going.

Navigating with double taps while video is paused freezes the image. As far as I can tell this is true of all ways of navigation while the video is paused

App crashes most of the time when exiting player after the image has frozen.

Absolutely in love with this app though. Excited to see it develop.

**Comment by Waffelatte** [comment]
Update, same stuff also happens with YouTube vids.

**Comment by lrorpilla** [comment]
This is related to the video player dependency that I use, which causes a lot of issues out of my control. I have been looking for solutions in the long term, though it is probably worth documenting this issue.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant lines in release notes.

- Fixed an issue where after viewing a video, new videos cannot be loaded up unless the application is killed and restarted.
