### ISSUE TITLE
Recursive lookups for monolingual definitions

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#9]
Some definitions in monolingual dictionaries point to other definitions and aren't that useful in their own. Here is an example.

もご-もご [1] （副）スル
（１）「もぐもぐ」に同じ。「―（と）かむ」
（２）うごめくさま。もぞもぞ。「着ぶくれて―する」

Would be great if I could click on もぐもぐ and see that definition.

**Comment by lrorpilla** [comment]
I have implemented this feature in [0.13.1](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.1-beta).

See the relevant line in the release notes:
* **Reinstated an enhancement make the definitions recursive only for monolingual definitions by making the text selectable<sup><b>\*</b></sup>**, if there is trouble closing the popup, click on the meaning or reading at the top

With that, I am closing this issue.

**Comment by ShiroiKuma0** [comment]
I've gone one-up on this functionality:

In my fork I've added full one-click searchability of all the dictionaries. In any dictionary search displayed - you click any word in the target language - it functions just like in the book, the dictionary shows you search for it.

It's in version 1.0.2
https://github.com/ShiroiKuma0/shiroikumanojisho
