### ISSUE TITLE
[Feature Request] Pause before each line and dual subs

### ISSUE THREAD

**Issue by ddc251992** [lrorpilla/jidoujisho#93]
I would love to be able to activate a mode while playing a video to train my reading ability.
1) Which would force the video to pause before each line so I could try to read it by myself and resume after a tap.
2) Also in addition to that it would be amazing if it would be possible to have duals subs while the second one would be blured or hidden and revealed it the user would tap twice (or something similar).

**Comment by lrorpilla** [comment]
For the first point, please refer to issue #42.

And for the next, I like to stay unopinionated, but I wouldn't recommend having the foreign language subtitles at all.
