### ISSUE TITLE
[Feature Request] option for more card types??

### ISSUE THREAD

**Issue by Waffelatte** [lrorpilla/jidoujisho#94]
I was thinking it would be fun to make some cards where the front is context audio only, and I could've sworn there was a way to do it with jidoujisho's card creator.

I bet it's already planned, but I would love to be able to select different card types for this kind of use.

**Comment by lrorpilla** [comment]
I can tell you this is in the works but for now, can't share any further.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant lines in release notes.

- Fields that are shown in the Card Creator may now be reordered and enabled according to user preference. The new Field system provides developers with a layer of abstraction should they wish to add a new exportable field that, for example, can be auto-generated upon selecting a certain word.
- Profiles allow users to switch between paradigms, and change Card Creator and Anki export preferences with the tap of a button.
- Each profile corresponds to a certain Anki model and mapping a user can set.
- Enhancements, Fields and Quick Actions are tied to Profiles. Users may use this to quickly switch between use cases.
- Users are no longer limited to using a pre-included jidoujisho Anki model, and may now use their own existing Anki models for card export. Users must map their Card Creator fields to the corresponding field for a given model.
