### ISSUE TITLE
Yomichan dictionary  giving error when importing

### ISSUE THREAD

**Issue by BradamantesAdvance** [lrorpilla/jidoujisho#95]
Hello,
Quoting the Readme page it says that "Users may import their own Yomichan custom dictionaries for offline use and instant lookups" Although I get an error when trying to do so. 
Basically I go to the "import dictionary" option and it opens up the window. Then I select the "yomichan term bank" option and browse my internal storage to find the JMdict.gz file but it gives me an "import error". Now I think i'm just dumb and can't figure it out but is there a list of supported dictionaries? I looked on the Yomichan page and this was one of them. Maybe JMdict is the one not working? 
If it's any help I'm using the jidousjisho_chisa-1_1_11_arm.apk version on android 9.

**Comment by T1CkShot** [comment]
Yeah you will need the zip format
you cant find them here

https://foosoft.net/projects/yomichan/

**Comment by BradamantesAdvance** [comment]
> Yeah you will need the zip format you can find them here
> 
> https://foosoft.net/projects/yomichan/



> Yeah you will need the zip format you can find them here
> 
> https://foosoft.net/projects/yomichan/

I did try both with the zip and extracted file  but still get the error.

**Comment by BradamantesAdvance** [comment]
Problem solved. 
Basically I would download the JMdict.gz file instead of downloading the jmdict_english.zip file which is the right one to download

**Comment by BradamantesAdvance** [comment]
Problem solved. Basically I would download the JMdict.gz file instead of downloading the jmdict_english.zip file which is the right one to download



> Yeah you will need the zip format you can find them here
> 
> https://foosoft.net/projects/yomichan/

Apparently I confused the .gz format and the zip one and only ever tried the .gz one.
