### ISSUE TITLE
"export card" button greyed out when trying to make anki cards. 

### ISSUE THREAD

**Issue by BradamantesAdvance** [lrorpilla/jidoujisho#96]
https://imgur.com/a/eJhLnDb 

I'm seen a bunch of people doing it on youtube and they just press export and it's done. Yet when I try it does nothing. I have Anki open in the background and enabled the API.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released.

If you can present that your issue is still present in the new version, feel free to open.
