### ISSUE TITLE
[Feature Request] integration of self hosted ttu-ttu ebook-reader

### ISSUE THREAD

**Issue by jacktheripper19** [lrorpilla/jidoujisho#97]
Hello,

recently the maintainers of ttu-ttu ebook-reader added the ability of self hosting the app instead of relying on the public instance. I wonder if it would be possible for jidoujisho to give the option of using the self hosted version as well in the book integration as a setting. 

It is possible though to use it from the browser, but then you get the browser shortcuts at the top all the time and you lose features like tapping words to get dictionary definitions.

Technically, one could just specify the url to the self hosted app and nothing would break since they are the same.

Thanks

**Comment by lrorpilla** [comment]
Smoother overall compatibility/streamlining of the reading experience and self-hosting is already in consideration.

You may fork the project to point to a self-hosted ttu if you so wish (you may simply change the URL in the application and compile the source), as the app is in a feature freeze until the next major release which I cannot currently share more details about at present.

Alternatively, I believe you can try to use a DNS redirect to always have the ttu domain point to your self-hosted instance.

**Comment by jacktheripper19** [comment]
Thanks, I might try your suggestion of changing the URL. Redirecting using DNS is not working for me because of issues with TLS certificates.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant line in the release notes.

- ッツ Ebook Reader is now locally run and included with the application. Users are no longer required to have an internet connection in order to use the reader, and will no longer be affected by site updates.
