### ISSUE TITLE
[Feature Request] Copy text from subtitles.

### ISSUE THREAD

**Issue by TriDyE** [lrorpilla/jidoujisho#98]
Please, add the possibility to copy text directly from subtitules in media player. Sometimes, it's neccesary to use a translator to translate an entire phrase, not only an specific word. Now, it's neccesary to create a new card from context or tap the phrase in subtitle list to generate text that you can copy, adding more steps to the process of copying a phrase. Thanks.

**Comment by lrorpilla** [comment]
The player has a Share Current Subtitle option you can use to quickly copy this to clipboard or share to any app

**Comment by TriDyE** [comment]
I didn't know about how that option works...and it's cool!

But, if the subtitle is too long and I need only part of it, it's too easy to select only what I want with one or two fingers and copy it.  Instead, if all the text is copied by default, later in translator I need to select what text I don't want before and after the text that I need to translate and delete it, adding too much work compared to using one finger to select, one tap to copy it and another tap to paste into translator.

I don,t know even if is possible or not to add this feature, but in meantime I'm gonna use 'share subtitle' option in menu.

Thanks a lot!!

**Comment by lrorpilla** [comment]
Issue has been addressed.
