### ISSUE TITLE
[Feature Request] Support for dictionaries from other languages

### ISSUE THREAD

**Issue by HarryPott3r** [lrorpilla/jidoujisho#99]
**Hello, brother!**

Please can you tell me if you have how to use dictionaries from other languages? If so, how would I do? It would be amazing if the media player behaves the learning of other languages. 
Friend, your application is simply fantastic and revolutionary! Thank you so much, from the bottom of my heart, because you created a fantastic app. I'm using it as a tool to save excerpts from videos that I want to save, as a relevant information dictates in a podcast, for example.
Honestly, I think this is the software with the greatest potential to transform the lives of someone from recent times: with it, besides being able to learn a language, there is this ability to send useful information easily to the spaced repetition system, which is very useful when consuming scientific content.

**Comment by lrorpilla** [comment]
Related issue and reply at **#107**. This is a duplicate so I might keep that thread open instead for discussion around supporting other languages.
